/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { AdvancedTransferState } from './enums/AdvancedTransferState';
import { AdvancedTransferType } from './enums/AdvancedTransferType';
import { BlindMatchMetadata } from './BlindMatchMetadata';
import { FundMovement } from './FundMovement';

/**
 * AdvancedTransfer represents a complex transfer operation such as a blind match settlement.
 */
export type AdvancedTransfer = {
  id?: string;
  /**
   * AdvancedTransferType specifies the type of advanced transfer.
   */
  type?: AdvancedTransferType;
  /**
   * AdvancedTransferState represents the lifecycle state of an advanced transfer.
   */
  state?: AdvancedTransferState;
  fundMovements?: Array<FundMovement>;
  /**
   * BlindMatchMetadata contains metadata specific to blind match advanced transfers.
   */
  blindMatchMetadata?: BlindMatchMetadata;
};
