/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { ConversionFeeTier } from './ConversionFeeTier';

/**
 * Per-pair conversion fee row: month-to-date net conversion volume and the applicable progressive fee tiers for an organization.
 */
export type ConversionFee = {
  /**
   * Source currency ticker.
   */
  fromCurrency?: string;
  /**
   * Destination currency ticker.
   */
  toCurrency?: string;
  /**
   * Month-to-date net conversion volume denominated in from_currency, aggregated at the owning organization level. Positive = net from->to, negative = net to->from.
   */
  netConversionVolumeMtd?: string;
  /**
   * Progressive fee tiers applicable to this organization for this pair. Tiers are ordered from lowest to highest threshold.
   */
  feeTiers?: Array<ConversionFeeTier>;
};
