/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { BlockchainAddress } from './BlockchainAddress';
import { TravelRuleData } from './TravelRuleData';

/**
 * Create a cross-asset wallet withdrawal: source asset is debited from the wallet and destination asset is delivered to the destination. The source amount is computed downstream based on the use case. The relationship between source and destination assets (bridge, swap, etc.) is an internal implementation detail and is not exposed on the wire.
 */
export type CreateCrossAssetWalletWithdrawalRequest = {
  /**
   * The idempotency key associated with the withdrawal
   */
  idempotencyKey: string;
  /**
   * The currency symbol debited from the wallet (e.g. \"USDC\")
   */
  sourceCurrencySymbol: string;
  /**
   * The currency symbol delivered to the destination (e.g. \"USDT\")
   */
  destinationCurrencySymbol: string;
  /**
   * Exact amount of destination_currency_symbol to deliver, in whole units. The corresponding source amount debited from the wallet is computed downstream.
   */
  destinationAmount: string;
  blockchainAddress: BlockchainAddress;
  travelRuleData?: TravelRuleData;
};
