/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { BlockchainAddress } from './BlockchainAddress';
import { CounterpartyDestination } from './CounterpartyDestination';
import { DestinationType } from './enums/DestinationType';
import { PaymentMethodDestination } from './PaymentMethodDestination';
import { TravelRuleData } from './TravelRuleData';

export type CreateWalletWithdrawalRequest = {
  /**
   * The amount in whole units of the withdrawal
   */
  amount: string;
  /**
   * - UNKNOWN_DESTINATION: nil value  - DESTINATION_PAYMENT_METHOD: A fiat bank account linked to a payment method id via Payment Method Service  - DESTINATION_BLOCKCHAIN: A blockchain network address  - DESTINATION_WALLET: An on platform wallet UUID NOTE: this is not usable in the withdrawals endpoint       only transfers  - DESTINATION_COUNTERPARTY: Counterparty ID
   */
  destinationType: DestinationType;
  /**
   * The idempotency key associated with the withdrawal
   */
  idempotencyKey: string;
  /**
   * The currency symbol for the withdrawal
   */
  currencySymbol: string;
  /**
   * Payment method destination details (required when destination_type is DESTINATION_PAYMENT_METHOD)
   */
  paymentMethod?: PaymentMethodDestination;
  /**
   * Blockchain address destination details (required when destination_type is DESTINATION_BLOCKCHAIN)
   */
  blockchainAddress?: BlockchainAddress;
  /**
   * Represents a destination for a counterparty payment
   */
  counterparty?: CounterpartyDestination;
  /**
   * Data object used for withdrawals.
   */
  travelRuleData?: TravelRuleData;
};
