/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { BlockchainAddress } from './BlockchainAddress';

/**
 * CreateCrossAssetWalletWithdrawalResponse is the response message for the CreateCrossAssetWalletWithdrawal RPC.
 */
export type CreateCrossAssetWalletWithdrawalResponse = {
  /**
   * The activity ID associated with the withdrawal (best-effort; may be empty)
   */
  activityId?: string;
  /**
   * A URL to the activity in the Prime application (best-effort; empty when activity_id is empty)
   */
  approvalUrl?: string;
  /**
   * The source currency symbol that was debited from the wallet
   */
  sourceSymbol?: string;
  /**
   * The amount of source_symbol debited from the wallet, computed downstream based on the use case
   */
  sourceAmount?: string;
  /**
   * The destination currency symbol delivered to the destination
   */
  destinationSymbol?: string;
  /**
   * The amount of destination_symbol delivered to the destination
   */
  destinationAmount?: string;
  blockchainDestination?: BlockchainAddress;
  /**
   * The id of the just created transaction
   */
  transactionId?: string;
};
