/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * XM 2.0 risk parameters for an asset tier.
 */
export type CrossMarginRiskParameters = {
  /**
   * Asset tier identifier.
   */
  assetTier?: string;
  /**
   * Base ratio for long positions.
   */
  baseRatioLong?: string;
  /**
   * Base ratio for short positions.
   */
  baseRatioShort?: string;
  /**
   * Volatility rate for long positions.
   */
  volatilityRateLong?: string;
  /**
   * Volatility rate for short positions.
   */
  volatilityRateShort?: string;
  /**
   * Volatility low threshold.
   */
  volatilityLowThreshold?: string;
  /**
   * Volatility high threshold.
   */
  volatilityHighThreshold?: string;
  /**
   * Liquidity A for long positions.
   */
  liquidityALong?: string;
  /**
   * Liquidity A for short positions.
   */
  liquidityAShort?: string;
  /**
   * Liquidity B for short positions.
   */
  liquidityBShort?: string;
  /**
   * Liquidity threshold.
   */
  liquidityThreshold?: string;
  /**
   * Basis offset credit rate.
   */
  basisOffsetCreditRate?: string;
};
