/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { CrossMarginPrimeDerivativesEquityBreakdown } from './CrossMarginPrimeDerivativesEquityBreakdown';
import { CrossMarginPrimeRiskNettingInfo } from './CrossMarginPrimeRiskNettingInfo';
import { CrossMarginPrimeSpotEquityBreakdown } from './CrossMarginPrimeSpotEquityBreakdown';
import { PrimeXMHealthStatus } from './enums/PrimeXMHealthStatus';
import { PrimeXMMarginCallThresholds } from './PrimeXMMarginCallThresholds';
import { PrimeXMMarginRequirementType } from './enums/PrimeXMMarginRequirementType';

/**
 * Cross-margin account summary and nested breakdowns.
 */
export type CrossMarginPrimeMarginSummary = {
  /**
   * Cross Margin Margin Requirement (XMMR) notional.
   */
  marginRequirement?: string;
  marginRequirementType?: PrimeXMMarginRequirementType;
  /**
   * Equity notional.
   */
  accountEquity?: string;
  /**
   * Equity - XMMR (margin excess is > 0).
   */
  marginExcessShortfall?: string;
  /**
   * Credit consumed from Cross Margin Credit Limit (XMCL).
   */
  consumedCredit?: string;
  /**
   * XM Credit Limit (XMCL) is the maximum notional USD of total fiat and digital asset loans.
   */
  xmCreditLimit?: string;
  /**
   * XM Margin Limit (XMML) is the maximum notional USD deficit.
   */
  xmMarginLimit?: string;
  /**
   * Amount of the XM margin limit consumed by excess deficit.
   */
  consumedMarginLimit?: string;
  /**
   * Equity attributed by spot.
   */
  spotEquity?: string;
  /**
   * Equity attributed by futures.
   */
  futuresEquity?: string;
  /**
   * Gross market value.
   */
  grossMarketValue?: string;
  /**
   * Net market value.
   */
  netMarketValue?: string;
  /**
   * Net exposure.
   */
  netExposure?: string;
  /**
   * Gross leverage.
   */
  grossLeverage?: string;
  spotEquityBreakdown?: CrossMarginPrimeSpotEquityBreakdown;
  derivativesEquityBreakdown?: CrossMarginPrimeDerivativesEquityBreakdown;
  riskNettingInfo?: CrossMarginPrimeRiskNettingInfo;
  healthStatus?: PrimeXMHealthStatus;
  /**
   * Equity ratio.
   */
  equityRatio?: string;
  /**
   * Deficit ratio.
   */
  deficitRatio?: string;
  marginThresholds?: PrimeXMMarginCallThresholds;
  /**
   * FCM excess available to return.
   */
  fcmExcessAvailableToReturn?: string;
};
