/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { CrossMarginPrimeDerivativesEquityBreakdown } from './CrossMarginPrimeDerivativesEquityBreakdown';
import { CrossMarginPrimeRiskNettingInfo } from './CrossMarginPrimeRiskNettingInfo';
import { CrossMarginPrimeSpotEquityBreakdown } from './CrossMarginPrimeSpotEquityBreakdown';
import { PrimeXMHealthStatus } from './enums/PrimeXMHealthStatus';
import { PrimeXMMarginCallThresholds } from './PrimeXMMarginCallThresholds';
import { PrimeXMMarginRequirementType } from './enums/PrimeXMMarginRequirementType';

/**
 * Cross-margin account summary and nested breakdowns.
 */
export type CrossMarginPrimeMarginSummary = {
  /**
   * Cross Margin Margin Requirement (XMMR) notional.
   */
  marginRequirement?: string;
  /**
   *  - MARGIN_REQUIREMENT_TYPE_DMR_PLUS_PMR: Integrated (netted) cross-margin requirement for spot assets and all derivatives contracts.  - MARGIN_REQUIREMENT_TYPE_IPMR_PLUS_IFMR: Combined cross-margin requirement: Integrated Portfolio Margin (IPMR) plus Ineligible Futures Margin (IFMR).
   */
  marginRequirementType?: PrimeXMMarginRequirementType;
  /**
   * Equity notional.
   */
  accountEquity?: string;
  /**
   * Equity - XMMR (margin excess is > 0).
   */
  marginExcessShortfall?: string;
  /**
   * Credit consumed from Cross Margin Credit Limit (XMCL).
   */
  consumedCredit?: string;
  /**
   * XM Credit Limit (XMCL) is the maximum notional USD of total fiat and digital asset loans.
   */
  xmCreditLimit?: string;
  /**
   * XM Margin Limit (XMML) is the maximum notional USD deficit.
   */
  xmMarginLimit?: string;
  /**
   * Amount of the XM margin limit consumed by excess deficit.
   */
  consumedMarginLimit?: string;
  /**
   * Equity attributed by spot.
   */
  spotEquity?: string;
  /**
   * Equity attributed by futures.
   */
  futuresEquity?: string;
  /**
   * Gross market value.
   */
  grossMarketValue?: string;
  /**
   * Net market value.
   */
  netMarketValue?: string;
  /**
   * Net exposure.
   */
  netExposure?: string;
  /**
   * Gross leverage.
   */
  grossLeverage?: string;
  /**
   * Breakdown of the components of spot equity.
   */
  spotEquityBreakdown?: CrossMarginPrimeSpotEquityBreakdown;
  /**
   * Breakdown of the components of derivatives equity.
   */
  derivativesEquityBreakdown?: CrossMarginPrimeDerivativesEquityBreakdown;
  /**
   * Groups XM margin requirement components, offset credits, and per-asset rows.
   */
  riskNettingInfo?: CrossMarginPrimeRiskNettingInfo;
  /**
   *  - HEALTH_STATUS_HEALTHY: Margin level is healthy.  - HEALTH_STATUS_WARNING: Margin level is breaching the warning threshold (WT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call (as defined in the margin methodology). WT is differentiated from DT in that it means margin health is approaching the UMCT.  - HEALTH_STATUS_CRITICAL: Margin level is breaching the UMCT and, as defined in the margin methodology, this will trigger an urgent margin call.  - HEALTH_STATUS_SUSPENDED: Trading and withdrawals are suspended per XM margin methodology.  - HEALTH_STATUS_RESTRICTED: Account is in a restricted state per XM margin methodology.  - HEALTH_STATUS_PRE_LIQUIDATION: Margin level is breaching the liquidation threshold (LT) and, as defined in the margin methodology, this will trigger the SESSION_LOCKED control status and liquidation may commence.  - HEALTH_STATUS_LIQUIDATING: Liquidation has commenced.  - HEALTH_STATUS_IN_DEFICIT: Margin level is breaching the deficit threshold (DT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call time (as defined in the margin methodology).
   */
  healthStatus?: PrimeXMHealthStatus;
  /**
   * Equity ratio.
   */
  equityRatio?: string;
  /**
   * Deficit ratio.
   */
  deficitRatio?: string;
  marginThresholds?: PrimeXMMarginCallThresholds;
  /**
   * FCM excess available to return.
   */
  fcmExcessAvailableToReturn?: string;
};
