/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * Breakdown of a position row\'s spot equity contribution. All values are zero when no contribution data is available. If the asset class is unknown, the contribution amounts are still returned.
 */
export type CrossMarginPrimeSpotMarginContribution = {
  /**
   * Signed spot value in USD after pending withdrawals, before collateral caps and cash-equivalent haircuts.
   */
  rawNotional?: string;
  /**
   * Long notional excluded above the collateral cap.
   */
  ineligibleNotional?: string;
  /**
   * Amount removed by the cash-equivalent long haircut.
   */
  haircutNotional?: string;
  /**
   * Final spot equity contribution. Positive values are eligible collateral; negative values are liabilities.
   */
  equityContribution?: string;
};
