/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { CrossMarginPrimeSpotMarginContribution } from './CrossMarginPrimeSpotMarginContribution';
import { PrimeXMAssetClass } from './enums/PrimeXMAssetClass';

/**
 * CrossMarginPrimeXMPosition is a single per-asset XM row (proto-backed fields from XMPositionDetails).
 */
export type CrossMarginPrimeXMPosition = {
  /**
   * Position currency
   */
  currency?: string;
  /**
   * Current market price
   */
  marketPrice?: string;
  /**
   * XM spot balance nominal
   */
  spotBalance?: string;
  /**
   * XM spot balance notional
   */
  spotBalanceNotional?: string;
  /**
   * XM futures balance nominal
   */
  futuresBalance?: string;
  /**
   * XM futures balance notional
   */
  futuresBalanceNotional?: string;
  /**
   * Base margin requirement notional
   */
  baseRequirement?: string;
  /**
   * Total margin required
   */
  totalPositionMargin?: string;
  /**
   * Basis offset credit applied to this asset row.
   */
  basisCredit?: string;
  /**
   * Post-netting USD notional for futures on this asset
   */
  futuresNettedNotional?: string;
  /**
   * Margin attributed to futures netting for this asset row.
   */
  futuresNettingMargin?: string;
  /**
   * Per-asset long amount from position_summary.
   */
  longAmount?: string;
  /**
   * Per-asset short amount from position_summary.
   */
  shortAmount?: string;
  /**
   * Volatility margin add-on for this asset.
   */
  volatilityAddon?: string;
  /**
   * Liquidity margin add-on for this asset.
   */
  liquidityAddon?: string;
  /**
   * Asset class of the XM position underlier.   - PRIME_XM_ASSET_CLASS_UNSPECIFIED: The asset class is unavailable for this position, or is not recognized by this API version.  - PRIME_XM_ASSET_CLASS_CASH: USD and USDC.  - PRIME_XM_ASSET_CLASS_FX: Non-USD fiat currencies recognized as FX in the margin model, such as EUR, GBP, and CHF.  - PRIME_XM_ASSET_CLASS_STABLECOIN: Non-USDC stablecoins recognized as cash equivalents in the margin model, such as EURC and USDT.  - PRIME_XM_ASSET_CLASS_CRYPTO: Crypto assets (e.g. BTC, ETH).
   */
  assetClass?: PrimeXMAssetClass;
  /**
   * Breakdown of a position row\'s spot equity contribution. All values are zero when no contribution data is available. If the asset class is unknown, the contribution amounts are still returned.
   */
  spotMarginContribution?: CrossMarginPrimeSpotMarginContribution;
};
