/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { ActiveLiquidationSummary } from './ActiveLiquidationSummary';
import { XMControlStatus } from './enums/XMControlStatus';
import { XMEntityCallStatus } from './enums/XMEntityCallStatus';
import { XMLoan } from './XMLoan';
import { XMMarginCall } from './XMMarginCall';
import { XMMarginLevel } from './enums/XMMarginLevel';
import { XMSummary } from './XMSummary';

export type CrossMarginOverview = {
  /**
   * XMControlStatus is a summarization of XM customer controls for trades and withdrawals
   */
  controlStatus?: XMControlStatus;
  /**
   * XMEntityCallStatus summarizes the state of open margin calls or debit calls. When multiple calls exist, the status reflects the highest priority call type. Priority order (highest to lowest): aged > urgent > standard > debit.   - ENTITY_NO_CALL: There are no margin calls or debit calls.  - ENTITY_OPEN_STANDARD_CALL: There is a standard margin call. There may also be debit calls, but there are no urgent margin calls or expired calls..  - ENTITY_OPEN_URGENT_CALL: There is an urgent margin call. There may also be standard margin calls or debit calls, but there are no expired calls.  - ENTITY_AGED_CALL: At least one open margin call (standard or urgent) or debit call is aged. This will trigger the SESSION_LOCKED control status.  - ENTITY_OPEN_DEBIT_CALL: There is a debit call. There are no standard margin calls, urgent margin calls, or expired calls.
   */
  callStatus?: XMEntityCallStatus;
  /**
   * XMMarginLevel is the realtime state of EQ/MR and MR-EQ monitored against XM thresholds as defined in the methodology
   */
  marginLevel?: XMMarginLevel;
  /**
   * XMSummary is the realtime evaluated XM margin model, containing positions and netting info
   */
  marginSummary?: XMSummary;
  /**
   * List of active XM margin calls
   */
  activeMarginCalls?: Array<XMMarginCall>;
  /**
   * List of active XM loans
   */
  activeLoans?: Array<XMLoan>;
  /**
   * ActiveLiquidationSummary provides a summary of the active or most recent XM liquidation
   */
  activeLiquidation?: ActiveLiquidationSummary;
};
