/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { DerivativeProductType } from './enums/DerivativeProductType';
import { FcmPositionSide } from './enums/FcmPositionSide';
import { OptionsDetails } from './OptionsDetails';

/**
 * A single derivative position across all derivative product types.
 */
export type DerivativePosition = {
  /**
   * Product ID
   */
  productId?: string;
  side?: FcmPositionSide;
  /**
   * Number of contracts
   */
  numberOfContracts?: string;
  /**
   * Daily realized PNL
   */
  dailyRealizedPnl?: string;
  /**
   * Unrealized PNL
   */
  unrealizedPnl?: string;
  /**
   * Current price of position
   */
  currentPrice?: string;
  /**
   * Average entry price
   */
  avgEntryPrice?: string;
  /**
   * Expiration time of position
   */
  expirationTime?: Date;
  /**
   * The general type of a derivative product.   - DERIVATIVE_PRODUCT_TYPE_UNSPECIFIED: Unknown product type.  - DERIVATIVE_PRODUCT_TYPE_SPOT: Spot product.  - DERIVATIVE_PRODUCT_TYPE_FUTURE: Future product.  - DERIVATIVE_PRODUCT_TYPE_EQUITY: Equity product.  - DERIVATIVE_PRODUCT_TYPE_PREDICTION_MARKET: Prediction market product.  - DERIVATIVE_PRODUCT_TYPE_OPTION: Option product.  - DERIVATIVE_PRODUCT_TYPE_BASIS: Basis product.  - DERIVATIVE_PRODUCT_TYPE_EQUITY_OPTION: Equity option product.  - DERIVATIVE_PRODUCT_TYPE_FUTURE_COMBO: Future combo product.  - DERIVATIVE_PRODUCT_TYPE_OPTION_COMBO: Option combo product.
   */
  productType?: DerivativeProductType;
  /**
   * Settlement currency
   */
  currency?: string;
  /**
   * Options-specific details for a derivative position, including greeks.
   */
  optionsDetails?: OptionsDetails;
  /**
   * Venue ID of the position
   */
  venueId?: string;
};
