/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type DetailedAddress = {
  /**
   * Primary address line
   */
  address1?: string;
  /**
   * Secondary address line (optional)
   */
  address2?: string;
  /**
   * Tertiary address line (optional)
   */
  address3?: string;
  /**
   * City name
   */
  city?: string;
  /**
   * State or province
   */
  state?: string;
  /**
   * ISO 3166-1 alpha-2 country code
   */
  countryCode?: string;
  /**
   * Postal/ZIP code
   */
  postalCode?: string;
};
