/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { FcmScheduledMaintenance } from './FcmScheduledMaintenance';
import { FcmTradingSessionClosedReason } from './enums/FcmTradingSessionClosedReason';
import { FcmTradingSessionState } from './enums/FcmTradingSessionState';

export type FcmTradingSessionDetails = {
  /**
   * Whether the trading session is currently open
   */
  sessionOpen?: boolean;
  /**
   * Trading session open time
   */
  openTime?: Date;
  /**
   * Trading session close time
   */
  closeTime?: Date;
  /**
   * FcmTradingSessionState represents the current state of an FCM trading session
   */
  sessionState?: FcmTradingSessionState;
  /**
   * Whether after-hours order entry is disabled
   */
  afterHoursOrderEntryDisabled?: boolean;
  /**
   * FcmTradingSessionClosedReason represents the reason for FCM trading session closure
   */
  closedReason?: FcmTradingSessionClosedReason;
  /**
   * FcmScheduledMaintenance contains scheduled maintenance window information
   */
  maintenance?: FcmScheduledMaintenance;
  /**
   * Settlement timestamp from previous trading day
   */
  settlementTimestamp?: Date;
  /**
   * Settlement price from previous trading day
   */
  settlementPrice?: string;
};
