/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { ContractExpiryType } from './enums/ContractExpiryType';
import { PerpetualProductDetails } from './PerpetualProductDetails';
import { RiskManagementType } from './enums/RiskManagementType';

export type FutureProductDetails = {
  /**
   * Contract code identifier
   */
  contractCode?: string;
  /**
   * Contract size
   */
  contractSize?: string;
  /**
   * Contract expiry timestamp
   */
  contractExpiry?: Date;
  /**
   * Contract root unit (underlying asset)
   */
  contractRootUnit?: string;
  /**
   * ContractExpiryType represents the expiry type of a futures contract
   */
  contractExpiryType?: ContractExpiryType;
  /**
   * RiskManagementType represents how risk is managed for a product
   */
  riskManagedBy?: RiskManagementType;
  /**
   * The venue this product trades on
   */
  venue?: string;
  /**
   * Descriptive name for the product group
   */
  groupDescription?: string;
  /**
   * IANA time zone for contract expiration
   */
  contractExpiryTimezone?: string;
  /**
   * Short version of the group description
   */
  groupShortDescription?: string;
  /**
   * PerpetualProductDetails contains details specific to perpetual futures products
   */
  perpetualDetails?: PerpetualProductDetails;
};
