/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { FcmMarginHealthState } from './enums/FcmMarginHealthState';

export type GetFcmRiskLimitsResponse = {
  /**
   * Risk Limit set for a client
   */
  cfmRiskLimit?: string;
  /**
   * Limit utilization calculated based on total margin and PnLs
   */
  cfmRiskLimitUtilization?: string;
  /**
   * The total margin required for both positions and open orders
   */
  cfmTotalMargin?: string;
  /**
   * Open Trade Equity accrued during the current trading session
   */
  cfmDeltaOte?: string;
  /**
   * Unsettled realized PNL for positions closed intraday
   */
  cfmUnsettledRealizedPnl?: string;
  /**
   * Unsettled accrued funding PNL from the last settlement
   */
  cfmUnsettledAccruedFundingPnl?: string;
  /**
   * Margin utilization as a decimal percentage between 0 and 1 (e.g. 0.5 means 50%)
   */
  marginUtilizationPercent?: string;
  /**
   * The margin health state of an FCM account.   - FCM_MARGIN_HEALTH_STATE_UNSPECIFIED: Unspecified margin health state.  - FCM_MARGIN_HEALTH_STATE_HEALTHY: Account margin is healthy.  - FCM_MARGIN_HEALTH_STATE_RESTRICTED: Account margin is restricted.  - FCM_MARGIN_HEALTH_STATE_PRE_LIQUIDATION: Account is approaching liquidation.  - FCM_MARGIN_HEALTH_STATE_LIQUIDATION: Account is in liquidation.
   */
  marginHealthState?: FcmMarginHealthState;
};
