/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { TravelRuleParty } from './TravelRuleParty';

export type GetTransactionTravelRuleDataResponse = {
  /**
   * Whether data requirements are fulfilled
   */
  fulfilled: boolean;
  /**
   * Whether the transfer is to/from a self-owned wallet
   */
  isSelf?: boolean;
  originator?: TravelRuleParty;
  beneficiary?: TravelRuleParty;
  /**
   * The crypto amount of the transaction (e.g. \"1.23 BTC\")
   */
  amount?: string;
  /**
   * The currency of the crypto amount
   */
  amountCurrency?: string;
  /**
   * The fiat amount of the transaction (e.g. \"123.45 USD\")
   */
  fiatAmount?: string;
  /**
   * The currency of the fiat amount
   */
  fiatAmountCurrency?: string;
  /**
   * The blockchain network for the transaction
   */
  blockchainNetwork?: string;
};
