/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { AssetBalance } from './AssetBalance';
import { LoanInfo } from './LoanInfo';
import { MarginAddOn } from './MarginAddOn';
import { MarginCallThresholds } from './MarginCallThresholds';
import { MarginControlStatus } from './enums/MarginControlStatus';
import { MarginHealthStatus } from './enums/MarginHealthStatus';
import { MarginLevel } from './enums/MarginLevel';
import { MarketRate } from './MarketRate';
import { PMAssetInfo } from './PMAssetInfo';

export type MarginSummary = {
  /**
   * The unique ID of the entity
   */
  entityId?: string;
  /**
   * The margin equity at the entity level. Margin Equity = LMV + SMV + Trading Cash Balance + Short Collateral - Pending Withdrawals
   */
  marginEquity?: string;
  /**
   * USD notional value of required equity in entity portfolios
   */
  marginRequirement?: string;
  /**
   * margin_equity - margin_requirement
   */
  excessDeficit?: string;
  /**
   * The raw amount of portfolio margin credit used
   */
  pmCreditConsumed?: string;
  /**
   * The maximum trade finance credit limit. This field is deprecated and will be removed in the future.
   */
  tfCreditLimit?: string;
  /**
   * The amount of trade finance credit used (USD). This field is deprecated and will be removed in the future.
   */
  tfCreditConsumed?: string;
  /**
   * TF Asset Adjusted Value (USD). This field is deprecated and will be removed in the future.
   */
  tfAdjustedAssetValue?: string;
  /**
   * TF Adjusted Liability Value (USD). This field is deprecated and will be removed in the future.
   */
  tfAdjustedLiabilityValue?: string;
  /**
   * The amount of adjusted credit used. This field is deprecated and will be removed in the future.
   */
  tfAdjustedCreditConsumed?: string;
  /**
   * The amount of adjusted equity. This field is deprecated and will be removed in the future.
   */
  tfAdjustedEquity?: string;
  /**
   * Whether or not a entity is frozen due to balance outstanding or other reason
   */
  frozen?: boolean;
  /**
   * The reason why a entity is frozen
   */
  frozenReason?: string;
  /**
   * Whether TF is enabled for the entity. This field is deprecated and will be removed in the future.
   */
  tfEnabled?: boolean;
  /**
   * Whether PM is enabled for the entity
   */
  pmEnabled?: boolean;
  /**
   * Market rates for the list of assets
   */
  marketRates?: Array<MarketRate>;
  /**
   * Asset Balances across portfolios
   */
  assetBalances?: Array<AssetBalance>;
  /**
   * Trade finance debit loan amounts. This field is deprecated and will be removed in the future.
   */
  tfLoans?: Array<LoanInfo>;
  /**
   * Portfolio Margin debit loan amounts
   */
  pmLoans?: Array<LoanInfo>;
  /**
   * Short collateral amounts
   */
  shortCollateral?: Array<LoanInfo>;
  /**
   * Gross market value (GMV) = LMV + Abs (SMV)
   */
  grossMarketValue?: string;
  /**
   * Net Market Value (NMV) = LMV + SMV
   */
  netMarketValue?: string;
  /**
   * Long Market Value (LMV) = Sum of positive notional for all assets
   */
  longMarketValue?: string;
  /**
   * Non_Marginable LMV: Sum of positive notional for each non-margin eligible coin
   */
  nonMarginableLongMarketValue?: string;
  /**
   * Short Market Value (SMV) = Sum of negative notional for each margin eligible coin
   */
  shortMarketValue?: string;
  /**
   * Gross Leverage = GMV / Margin Requirement
   */
  grossLeverage?: string;
  /**
   * Net Exposure = (LMV + SMV) / GMV
   */
  netExposure?: string;
  portfolioStressTriggered?: MarginAddOn;
  /**
   * PM asset info netted across the entity
   */
  pmAssetInfo?: Array<PMAssetInfo>;
  /**
   * PM limit that monitors gross notional borrowings (crypto + fiat)
   */
  pmCreditLimit?: string;
  /**
   * PM limit that monitors excess deficit
   */
  pmMarginLimit?: string;
  /**
   * The amount of the margin limit that is consumed by the excess deficit
   */
  pmMarginConsumed?: string;
  /**
   * Cash moved by the short-collateral rehypothecation sweep for this conversion. Only populated for historical margin summaries.
   */
  shortCollateralTransfer?: string;
  /**
   * MarginHealthStatus is the recorded (sticky) margin health state for an entity.   - MARGIN_HEALTH_STATUS_HEALTHY: Margin level is healthy.  - MARGIN_HEALTH_STATUS_WARNING: Margin level is breaching the warning threshold (WT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call (as defined in the margin methodology). WT is differentiated from DT in that it means margin health is approaching the UMCT.  - MARGIN_HEALTH_STATUS_CRITICAL: Margin level is breaching the UMCT and, as defined in the margin methodology, this will trigger an urgent margin call.  - MARGIN_HEALTH_STATUS_SUSPENDED: Trading and withdrawals are suspended per the margin methodology.  - MARGIN_HEALTH_STATUS_RESTRICTED: Account is in a restricted state per the margin methodology.  - MARGIN_HEALTH_STATUS_PRE_LIQUIDATION: Margin level is breaching the liquidation threshold (LT) and, as defined in the margin methodology, this will trigger the SESSION_LOCKED control status and liquidation may commence.  - MARGIN_HEALTH_STATUS_LIQUIDATING: Liquidation has commenced.  - MARGIN_HEALTH_STATUS_IN_DEFICIT: Margin level is breaching the deficit threshold (DT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call time (as defined in the margin methodology).
   */
  healthStatus?: MarginHealthStatus;
  /**
   * MarginLevel is the realtime state of EQ/MR and MR-EQ monitored against thresholds as defined in the methodology.   - MARGIN_LEVEL_HEALTHY: Margin level is healthy  - MARGIN_LEVEL_DEFICIT: Margin level is breaching the deficit threshold (DT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call time (as defined in the margin methodology)  - MARGIN_LEVEL_WARNING: Margin level is breaching the warning threshold (WT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call (as defined in the margin methodology). WT is differentiated from DT in that it means margin health is approaching the UMCT  - MARGIN_LEVEL_URGENT_MARGIN_CALL: Margin level is breaching the UMCT and, as defined in the margin methodology, this will trigger an urgent margin call  - MARGIN_LEVEL_LIQUIDATION: Margin level is breaching the liquidation threshold (LT) and, as defined in the margin methodology, this will trigger the SESSION_LOCKED control status and liquidation may commence.
   */
  marginLevel?: MarginLevel;
  /**
   * MarginCallThresholds are the thresholds backing the margin level evaluation.
   */
  marginThresholds?: MarginCallThresholds;
  /**
   * MarginControlStatus is a summarization of customer controls for trades and withdrawals.   - MARGIN_CONTROL_STATUS_TRADES_AND_WITHDRAWALS: Allowed to trade and withdraw. See the margin methodology for full description of when trading and withdrawals are enabled or disabled.  - MARGIN_CONTROL_STATUS_TRADES_ONLY: Allowed to trade but not withdraw. See the margin methodology for full description of when trading and withdrawals are enabled or disabled.  - MARGIN_CONTROL_STATUS_SESSION_LOCKED: Not allowed to trade or withdraw. See the margin methodology for full description of when trading and withdrawals are enabled or disabled.
   */
  controlStatus?: MarginControlStatus;
  /**
   * Equity ratio.
   */
  equityRatio?: string;
  /**
   * Deficit ratio.
   */
  deficitRatio?: string;
};
