/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { OptionType } from './enums/OptionType';
import { PriceIncrementStep } from './PriceIncrementStep';
import { SettlementModel } from './enums/SettlementModel';
import { SettlementPeriod } from './enums/SettlementPeriod';

export type OptionProductDetails = {
  /**
   * The type of an option position.   - OPTION_TYPE_UNSPECIFIED: Unspecified option type.  - OPTION_TYPE_CALL: Call option.  - OPTION_TYPE_PUT: Put option.
   */
  optionType?: OptionType;
  /**
   * Strike price of the option
   */
  strike?: string;
  /**
   * Contract root unit (underlying asset)
   */
  contractRootUnit?: string;
  /**
   * Currency the option settles in
   */
  settlementCurrency?: string;
  /**
   * Contract code identifier
   */
  contractCode?: string;
  /**
   * Descriptive name for the product group
   */
  groupDescription?: string;
  /**
   * Contract size
   */
  contractSize?: string;
  /**
   * Contract expiry timestamp
   */
  contractExpiry?: Date;
  /**
   * SettlementPeriod represents how often a derivative contract expires and settles
   */
  settlementPeriod?: SettlementPeriod;
  /**
   * SettlementModel represents the currency a derivative contract settles in
   */
  settlementModel?: SettlementModel;
  /**
   * Currency the option is quoted against
   */
  counterCurrency?: string;
  /**
   * Smallest tradable quantity of the contract
   */
  lotSize?: string;
  /**
   * Tiered price increments that override price_increment above a threshold; empty when a single price_increment applies
   */
  priceIncrementSteps?: Array<PriceIncrementStep>;
};
