/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type OrderEdit = {
  /**
   * New price for the edited order
   */
  price?: string;
  /**
   * New base quantity for the edited order, populated if order is in base size
   */
  baseQuantity?: string;
  /**
   * New quote value for the edited order, populated if order is in quote size
   */
  quoteValue?: string;
  /**
   * Display base size for the edited order, populated if order is in base size
   */
  displayBaseSize?: string;
  /**
   * Display quote size for the edited order, populated if order is in quote size
   */
  displayQuoteSize?: string;
  /**
   * New stop price for the edited order
   */
  stopPrice?: string;
  /**
   * New expiry/end time for the edited order
   */
  expiryTime?: Date;
  /**
   * Time when the edit was accepted
   */
  acceptTime?: Date;
  /**
   * The new client order identifier that the order adopted after the replacement was successfully accepted
   */
  clientOrderId?: string;
};
