/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type QuoteResponse = {
  quoteId?: string;
  expirationTime?: Date;
  bestPrice?: string;
  /**
   * total quote amount for previewing
   */
  orderTotal?: string;
  priceInclusiveOfFees?: string;
  /**
   * Echo of the quote_duration_ms supplied in the request. 0 if the client did not supply a value, in which case the server applies the default of 3000 ms (3 seconds).
   */
  quoteDurationMs?: string;
};
