/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { OrderSide } from './enums/OrderSide';

/**
 * based off PostOrderPreviewRequest
 */
export type RFQ = {
  /**
   * The ID of the product being traded for the order (e.g. `BTC-USD`)
   */
  productId: string;
  side: OrderSide;
  /**
   * A client-generated order ID used for reference purposes (note: order will be rejected if this ID is not unique among all currently active orders)
   */
  clientQuoteId: string;
  /**
   * Order size in base asset units (either `base_quantity` or `quote_value` is required)
   */
  baseQuantity?: string;
  /**
   * Order size in quote asset units, i.e. the amount the user wants to spend (when buying) or receive (when selling); the quantity in base units will be determined based on the market liquidity and indicated `quote_value` (either `base_quantity` or `quote_value` is required)
   */
  quoteValue?: string;
  /**
   * The limit price
   */
  limitPrice: string;
  /**
   * The currency in which the settlement will be made
   */
  settlCurrency?: string;
  /**
   * Optional quote timeout in milliseconds. Defaults to 3000 ms (3 seconds) if not specified. Maximum allowed value is 30000 ms (30 seconds); requests with a larger value are rejected. Mirrors FIX tag 8090 (QuoteRequestGoodForMs).
   */
  quoteDurationMs?: string;
};
