/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * Response containing encrypted credentials for the newly created API key. Decrypt using your current secret_key with HKDF-SHA256 + AES-256-GCM. See the Rotate API Key guide for decryption instructions.
 */
export type RotateAPIKeyResponse = {
  /**
   * Base64-encoded encrypted payload containing new API key credentials. Wire format after base64 decode: version(1 byte) | salt(32 bytes) | nonce(12 bytes) | ciphertext+tag.
   */
  encryptedCredentials?: string;
  /**
   * The Prime activity ID tracking the consensus approval for this rotation. Use with the Activities endpoints to monitor approval status.
   */
  activityId?: string;
};
