/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { DetailedAddress } from './DetailedAddress';
import { NaturalPersonName } from './NaturalPersonName';
import { TravelRuleWalletType } from './enums/TravelRuleWalletType';
import { GoogleTypeDate } from './googleTypeDate';

/**
 * Represents a party in a travel rule transfer (originator or beneficiary).
 */
export type TravelRuleParty = {
  /**
   * Legal name (for entities or simple name format)
   */
  name?: string;
  /**
   * Natural person name components
   */
  naturalPersonName?: NaturalPersonName;
  /**
   * Detailed address information
   */
  address?: DetailedAddress;
  /**
   * Type of wallet being used for transfers
   */
  walletType?: TravelRuleWalletType;
  /**
   * VASP identifier when wallet_type is VASP
   */
  vaspId?: string;
  /**
   * VASP name fallback when vasp_id is unknown
   */
  vaspName?: string;
  /**
   * Personal identifier for travel rule compliance. For individuals: passport number, national ID, driver\'s license. For institutions: LEI (Legal Entity Identifier).
   */
  personalId?: string;
  /**
   * Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following:
   */
  dateOfBirth?: GoogleTypeDate;
  /**
   * Telephone number for contact purposes.
   */
  telephoneNumber?: string;
  /**
   * Account identifier for travel rule compliance. If not provided, defaults to portfolio ID.
   */
  accountId?: string;
  /**
   * Detailed address information
   */
  vaspAddress?: DetailedAddress;
};
