/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type UpdateFundingSettingsRequest = {
  /**
   * Set the Derivatives Funding Portfolio that will be used to fund FCM margin calls and receive excess margin sweeps. Only one portfolio per entity.
   */
  designatedFundingPortfolioId: string;
  /**
   * When true, USDC in your Derivatives Funding Portfolio will be converted to USD to meet FCM margin calls (Auto-Convert USDC).
   */
  automaticConversionEnabled: boolean;
  /**
   * Deprecated: Auto-Initiate Loans is now always enabled for Financing customers. Any value sent for this field is ignored.
   */
  automaticLoanEnabled?: boolean;
  /**
   * When true, any FCM account balance above your margin requirements will be automatically swept back to your Derivatives funding portfolio. (Auto-Return Excess Margin)
   */
  automaticExcessReturnEnabled: boolean;
  /**
   * Weekend Buying Power: Setting a target amount to maintain in your Futures account above margin requirements. You can only withdraw funds in excess of this amount.
   */
  excessFundsTargetAmount: string;
};
