/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { Network } from './Network';
import { WalletType } from './enums/WalletType';
import { WalletVisibility } from './enums/WalletVisibility';

export type Wallet = {
  /**
   * The unique UUID for the wallet
   */
  id?: string;
  /**
   * The name of the wallet
   */
  name?: string;
  /**
   * The asset stored in the wallet
   */
  symbol?: string;
  /**
   * Indicates the wallet type
   */
  type?: WalletType;
  /**
   * The UTC timestamp when this wallet was created
   */
  createdAt?: Date;
  /**
   * The active address of the wallet
   */
  address?: string;
  visibility?: WalletVisibility;
  network?: Network;
};
