/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { XMLiquidatedAsset } from './XMLiquidatedAsset';
import { XMLiquidationStatus } from './enums/XMLiquidationStatus';
import { XMSummary } from './XMSummary';

export type XMLiquidationDetail = {
  /**
   * Financing liquidation UUID
   */
  liquidationId?: string;
  /**
   * XMLiquidationStatus is the current status of an XM liquidation
   */
  status?: XMLiquidationStatus;
  /**
   * USD notional shortfall amount that triggered the liquidation
   */
  shortfallAmount?: string;
  /**
   * Timestamp when the pre-liquidation phase started
   */
  preLiquidationStartTime?: Date;
  /**
   * XMSummary is the realtime evaluated XM margin model, containing positions and netting info
   */
  marginSummary?: XMSummary;
  /**
   * Timestamp when active liquidation started
   */
  liquidationStartTime?: Date;
  /**
   * USD notional amount that has been filled so far
   */
  filledAmount?: string;
  /**
   * USD notional amount remaining to be liquidated
   */
  remainingAmount?: string;
  /**
   * Timestamp when the liquidation finished
   */
  liquidationFinishTime?: Date;
  /**
   * Per-asset breakdown of liquidated amounts
   */
  assetBreakdown?: Array<XMLiquidatedAsset>;
};
