/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * The margin health state of an FCM account.   - FCM_MARGIN_HEALTH_STATE_UNSPECIFIED: Unspecified margin health state.  - FCM_MARGIN_HEALTH_STATE_HEALTHY: Account margin is healthy.  - FCM_MARGIN_HEALTH_STATE_RESTRICTED: Account margin is restricted.  - FCM_MARGIN_HEALTH_STATE_PRE_LIQUIDATION: Account is approaching liquidation.  - FCM_MARGIN_HEALTH_STATE_LIQUIDATION: Account is in liquidation.
 */
export enum FcmMarginHealthState {
  FcmMarginHealthStateHealthy = 'FCM_MARGIN_HEALTH_STATE_HEALTHY',
  FcmMarginHealthStateRestricted = 'FCM_MARGIN_HEALTH_STATE_RESTRICTED',
  FcmMarginHealthStatePreLiquidation = 'FCM_MARGIN_HEALTH_STATE_PRE_LIQUIDATION',
  FcmMarginHealthStateLiquidation = 'FCM_MARGIN_HEALTH_STATE_LIQUIDATION',
}
