/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * Ratio used to evaluate a threshold. Rules are evaluated in configured order; the first matching rule determines the margin level when equity is below the margin requirement. A zero threshold imposes no constraint for that ratio. If the denominator is zero, the evaluator skips the division and checks the numerator condition: nonnegative equity for an equity-ratio rule, or a positive deficit for a deficit-ratio rule.   - MARGIN_THRESHOLD_TYPE_UNSPECIFIED: No threshold type is provided.  - MARGIN_THRESHOLD_TYPE_EQUITY_RATIO: For a nonzero threshold and positive margin requirement, the rule matches when equity is nonnegative and equity / margin requirement is greater than or equal to threshold_value.  - MARGIN_THRESHOLD_TYPE_DEFICIT_RATIO: For a nonzero threshold and positive margin limit, the rule matches when the deficit is positive and (margin requirement - equity) / margin limit is greater than threshold_value.  - MARGIN_THRESHOLD_TYPE_NONE: Fallback rule with no numeric ratio threshold.
 */
export enum MarginThresholdMarginThresholdType {
  MarginThresholdTypeEquityRatio = 'MARGIN_THRESHOLD_TYPE_EQUITY_RATIO',
  MarginThresholdTypeDeficitRatio = 'MARGIN_THRESHOLD_TYPE_DEFICIT_RATIO',
  MarginThresholdTypeNone = 'MARGIN_THRESHOLD_TYPE_NONE',
}
