/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * MarginThresholdType indicates whether the threshold value is an equity ratio, a deficit ratio, or none.   - MARGIN_THRESHOLD_TYPE_EQUITY_RATIO: Threshold based on equity ratio EQ / MR; triggers when EQ / MR >= threshold_value.  - MARGIN_THRESHOLD_TYPE_DEFICIT_RATIO: Threshold based on deficit ratio (MR - EQ) / margin_limit; triggers when (MR - EQ) / margin_limit > threshold_value.  - MARGIN_THRESHOLD_TYPE_NONE: No ER/DR threshold, terminal threshold to match any unhealthy state.
 */
export enum MarginThresholdMarginThresholdType {
  MarginThresholdTypeEquityRatio = 'MARGIN_THRESHOLD_TYPE_EQUITY_RATIO',
  MarginThresholdTypeDeficitRatio = 'MARGIN_THRESHOLD_TYPE_DEFICIT_RATIO',
  MarginThresholdTypeNone = 'MARGIN_THRESHOLD_TYPE_NONE',
}
