/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * Trading and withdrawal permissions derived from the account\'s recorded health state, outstanding margin calls, and account restrictions. These permissions can remain restricted even when the calculated `margin_level` improves. Returns `MARGIN_CONTROL_STATUS_UNSPECIFIED` when the margin service doesn\'t provide a control status.   - MARGIN_CONTROL_STATUS_UNSPECIFIED: No control status is provided. Don\'t infer permission to trade or withdraw from this value.  - MARGIN_CONTROL_STATUS_TRADES_AND_WITHDRAWALS: Allowed to trade and withdraw under the applicable margin methodology.  - MARGIN_CONTROL_STATUS_TRADES_ONLY: Allowed to trade but not withdraw under the applicable margin methodology.  - MARGIN_CONTROL_STATUS_SESSION_LOCKED: Not allowed to trade or withdraw.
 */
export enum MarginControlStatus {
  MarginControlStatusTradesAndWithdrawals = 'MARGIN_CONTROL_STATUS_TRADES_AND_WITHDRAWALS',
  MarginControlStatusTradesOnly = 'MARGIN_CONTROL_STATUS_TRADES_ONLY',
  MarginControlStatusSessionLocked = 'MARGIN_CONTROL_STATUS_SESSION_LOCKED',
}
