/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * Asset class of the XM position underlier.   - PRIME_XM_ASSET_CLASS_UNSPECIFIED: The asset class is unavailable for this position, or is not recognized by this API version.  - PRIME_XM_ASSET_CLASS_CASH: USD and USDC.  - PRIME_XM_ASSET_CLASS_FX: Non-USD fiat currencies recognized as FX in the margin model, such as EUR, GBP, and CHF.  - PRIME_XM_ASSET_CLASS_STABLECOIN: Non-USDC stablecoins recognized as cash equivalents in the margin model, such as EURC and USDT.  - PRIME_XM_ASSET_CLASS_CRYPTO: Crypto assets (e.g. BTC, ETH).
 */
export enum PrimeXMAssetClass {
  PrimeXmAssetClassUnspecified = 'PRIME_XM_ASSET_CLASS_UNSPECIFIED',
  PrimeXmAssetClassCash = 'PRIME_XM_ASSET_CLASS_CASH',
  PrimeXmAssetClassFx = 'PRIME_XM_ASSET_CLASS_FX',
  PrimeXmAssetClassStablecoin = 'PRIME_XM_ASSET_CLASS_STABLECOIN',
  PrimeXmAssetClassCrypto = 'PRIME_XM_ASSET_CLASS_CRYPTO',
}
