/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum SendWebhookSimulationBadRequestSubcode {
  SendWebhookSimulationBadRequestEntityIdRequired = 'SEND_WEBHOOK_SIMULATION_BAD_REQUEST_ENTITY_ID_REQUIRED',
  SendWebhookSimulationBadRequestEntityIdInvalid = 'SEND_WEBHOOK_SIMULATION_BAD_REQUEST_ENTITY_ID_INVALID',
  SendWebhookSimulationBadRequestPortfolioIdRequired = 'SEND_WEBHOOK_SIMULATION_BAD_REQUEST_PORTFOLIO_ID_REQUIRED',
  SendWebhookSimulationBadRequestPortfolioIdInvalid = 'SEND_WEBHOOK_SIMULATION_BAD_REQUEST_PORTFOLIO_ID_INVALID',
  SendWebhookSimulationBadRequestWebhookSubscriptionIdRequired = 'SEND_WEBHOOK_SIMULATION_BAD_REQUEST_WEBHOOK_SUBSCRIPTION_ID_REQUIRED',
  SendWebhookSimulationBadRequestWebhookEventTypeInvalid = 'SEND_WEBHOOK_SIMULATION_BAD_REQUEST_WEBHOOK_EVENT_TYPE_INVALID',
}
