/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * - SETTLEMENT_PERIOD_UNSPECIFIED: Unspecified settlement period  - SETTLEMENT_PERIOD_PERPETUAL: Contract never expires  - SETTLEMENT_PERIOD_DAY: Contract expires daily  - SETTLEMENT_PERIOD_WEEK: Contract expires weekly  - SETTLEMENT_PERIOD_MONTH: Contract expires monthly
 */
export enum SettlementPeriod {
  SettlementPeriodPerpetual = 'SETTLEMENT_PERIOD_PERPETUAL',
  SettlementPeriodDay = 'SETTLEMENT_PERIOD_DAY',
  SettlementPeriodWeek = 'SETTLEMENT_PERIOD_WEEK',
  SettlementPeriodMonth = 'SETTLEMENT_PERIOD_MONTH',
}
