/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum UpdateWebhookSubscriptionBadRequestSubcode {
  UpdateWebhookSubscriptionBadRequestEntityIdRequired = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_ENTITY_ID_REQUIRED',
  UpdateWebhookSubscriptionBadRequestEntityIdInvalid = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_ENTITY_ID_INVALID',
  UpdateWebhookSubscriptionBadRequestPortfolioIdRequired = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_PORTFOLIO_ID_REQUIRED',
  UpdateWebhookSubscriptionBadRequestPortfolioIdInvalid = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_PORTFOLIO_ID_INVALID',
  UpdateWebhookSubscriptionBadRequestWebhookSubscriptionIdRequired = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_WEBHOOK_SUBSCRIPTION_ID_REQUIRED',
  UpdateWebhookSubscriptionBadRequestWebhookTargetUrlInvalid = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_WEBHOOK_TARGET_URL_INVALID',
  UpdateWebhookSubscriptionBadRequestWebhookEventTypeInvalid = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_WEBHOOK_EVENT_TYPE_INVALID',
  UpdateWebhookSubscriptionBadRequestWebhookVersionConflict = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_WEBHOOK_VERSION_CONFLICT',
  UpdateWebhookSubscriptionBadRequestWebhookInvalidArgument = 'UPDATE_WEBHOOK_SUBSCRIPTION_BAD_REQUEST_WEBHOOK_INVALID_ARGUMENT',
}
