/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * ValidatorProvider enumerates the ETH validator service providers accepted for unstaking.
 */
export enum ValidatorProvider {
  ValidatorProviderCoinbaseCloud = 'VALIDATOR_PROVIDER_COINBASE_CLOUD',
  ValidatorProviderMavan = 'VALIDATOR_PROVIDER_MAVAN',
  ValidatorProviderFigment = 'VALIDATOR_PROVIDER_FIGMENT',
  ValidatorProviderCodefi = 'VALIDATOR_PROVIDER_CODEFI',
  ValidatorProviderAttestant = 'VALIDATOR_PROVIDER_ATTESTANT',
  ValidatorProviderGalaxy = 'VALIDATOR_PROVIDER_GALAXY',
}
