/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { ListWeb3WalletBalancesNotFoundSubcode } from './enums/ListWeb3WalletBalancesNotFoundSubcode';
import { NotFoundErrorCode } from './enums/NotFoundErrorCode';

/**
 * ListWeb3WalletBalancesNotFoundErrorResponse documents the HTTP 404 error body.
 */
export type ListWeb3WalletBalancesNotFoundErrorResponse = {
  code?: NotFoundErrorCode;
  message?: string;
  subcode?: ListWeb3WalletBalancesNotFoundSubcode;
  traceId?: string;
};
