/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import type { AcceptQuoteBadRequestErrorResponse } from './AcceptQuoteBadRequestErrorResponse';
import type { AcceptQuoteForbiddenErrorResponse } from './AcceptQuoteForbiddenErrorResponse';
import type { AcceptQuoteNotFoundErrorResponse } from './AcceptQuoteNotFoundErrorResponse';
import type { CancelAdvancedTransferBadRequestErrorResponse } from './CancelAdvancedTransferBadRequestErrorResponse';
import type { CancelAdvancedTransferForbiddenErrorResponse } from './CancelAdvancedTransferForbiddenErrorResponse';
import type { CancelAdvancedTransferNotFoundErrorResponse } from './CancelAdvancedTransferNotFoundErrorResponse';
import type { CancelFuturesSweepBadRequestErrorResponse } from './CancelFuturesSweepBadRequestErrorResponse';
import type { CancelFuturesSweepForbiddenErrorResponse } from './CancelFuturesSweepForbiddenErrorResponse';
import type { CancelFuturesSweepNotFoundErrorResponse } from './CancelFuturesSweepNotFoundErrorResponse';
import type { CancelOrderBadRequestErrorResponse } from './CancelOrderBadRequestErrorResponse';
import type { CancelOrderForbiddenErrorResponse } from './CancelOrderForbiddenErrorResponse';
import type { CancelOrderNotFoundErrorResponse } from './CancelOrderNotFoundErrorResponse';
import type { CreateAdvancedTransferBadRequestErrorResponse } from './CreateAdvancedTransferBadRequestErrorResponse';
import type { CreateAdvancedTransferForbiddenErrorResponse } from './CreateAdvancedTransferForbiddenErrorResponse';
import type { CreateAdvancedTransferNotFoundErrorResponse } from './CreateAdvancedTransferNotFoundErrorResponse';
import type { CreateAllocationBadRequestErrorResponse } from './CreateAllocationBadRequestErrorResponse';
import type { CreateAllocationForbiddenErrorResponse } from './CreateAllocationForbiddenErrorResponse';
import type { CreateAllocationNotFoundErrorResponse } from './CreateAllocationNotFoundErrorResponse';
import type { CreateConversionBadRequestErrorResponse } from './CreateConversionBadRequestErrorResponse';
import type { CreateConversionForbiddenErrorResponse } from './CreateConversionForbiddenErrorResponse';
import type { CreateConversionNotFoundErrorResponse } from './CreateConversionNotFoundErrorResponse';
import type { CreateNetAllocationBadRequestErrorResponse } from './CreateNetAllocationBadRequestErrorResponse';
import type { CreateNetAllocationForbiddenErrorResponse } from './CreateNetAllocationForbiddenErrorResponse';
import type { CreateNetAllocationNotFoundErrorResponse } from './CreateNetAllocationNotFoundErrorResponse';
import type { CreateOnchainAddressGroupBadRequestErrorResponse } from './CreateOnchainAddressGroupBadRequestErrorResponse';
import type { CreateOnchainAddressGroupForbiddenErrorResponse } from './CreateOnchainAddressGroupForbiddenErrorResponse';
import type { CreateOnchainAddressGroupNotFoundErrorResponse } from './CreateOnchainAddressGroupNotFoundErrorResponse';
import type { CreateOnchainTransactionBadRequestErrorResponse } from './CreateOnchainTransactionBadRequestErrorResponse';
import type { CreateOnchainTransactionForbiddenErrorResponse } from './CreateOnchainTransactionForbiddenErrorResponse';
import type { CreateOnchainTransactionNotFoundErrorResponse } from './CreateOnchainTransactionNotFoundErrorResponse';
import type { CreateOrderBadRequestErrorResponse } from './CreateOrderBadRequestErrorResponse';
import type { CreateOrderForbiddenErrorResponse } from './CreateOrderForbiddenErrorResponse';
import type { CreateOrderNotFoundErrorResponse } from './CreateOrderNotFoundErrorResponse';
import type { CreatePortfolioAddressBookEntryBadRequestErrorResponse } from './CreatePortfolioAddressBookEntryBadRequestErrorResponse';
import type { CreatePortfolioAddressBookEntryForbiddenErrorResponse } from './CreatePortfolioAddressBookEntryForbiddenErrorResponse';
import type { CreatePortfolioAddressBookEntryNotFoundErrorResponse } from './CreatePortfolioAddressBookEntryNotFoundErrorResponse';
import type { CreateQuoteRequestBadRequestErrorResponse } from './CreateQuoteRequestBadRequestErrorResponse';
import type { CreateQuoteRequestForbiddenErrorResponse } from './CreateQuoteRequestForbiddenErrorResponse';
import type { CreateQuoteRequestNotFoundErrorResponse } from './CreateQuoteRequestNotFoundErrorResponse';
import type { CreateWalletBadRequestErrorResponse } from './CreateWalletBadRequestErrorResponse';
import type { CreateWalletDepositAddressBadRequestErrorResponse } from './CreateWalletDepositAddressBadRequestErrorResponse';
import type { CreateWalletDepositAddressForbiddenErrorResponse } from './CreateWalletDepositAddressForbiddenErrorResponse';
import type { CreateWalletDepositAddressNotFoundErrorResponse } from './CreateWalletDepositAddressNotFoundErrorResponse';
import type { CreateWalletForbiddenErrorResponse } from './CreateWalletForbiddenErrorResponse';
import type { CreateWalletNotFoundErrorResponse } from './CreateWalletNotFoundErrorResponse';
import type { CreateWalletTransferBadRequestErrorResponse } from './CreateWalletTransferBadRequestErrorResponse';
import type { CreateWalletTransferForbiddenErrorResponse } from './CreateWalletTransferForbiddenErrorResponse';
import type { CreateWalletTransferNotFoundErrorResponse } from './CreateWalletTransferNotFoundErrorResponse';
import type { CreateWalletWithdrawalBadRequestErrorResponse } from './CreateWalletWithdrawalBadRequestErrorResponse';
import type { CreateWalletWithdrawalForbiddenErrorResponse } from './CreateWalletWithdrawalForbiddenErrorResponse';
import type { CreateWalletWithdrawalNotFoundErrorResponse } from './CreateWalletWithdrawalNotFoundErrorResponse';
import type { DeleteOnchainAddressGroupBadRequestErrorResponse } from './DeleteOnchainAddressGroupBadRequestErrorResponse';
import type { DeleteOnchainAddressGroupForbiddenErrorResponse } from './DeleteOnchainAddressGroupForbiddenErrorResponse';
import type { DeleteOnchainAddressGroupNotFoundErrorResponse } from './DeleteOnchainAddressGroupNotFoundErrorResponse';
import type { EditOrderBadRequestErrorResponse } from './EditOrderBadRequestErrorResponse';
import type { EditOrderForbiddenErrorResponse } from './EditOrderForbiddenErrorResponse';
import type { EditOrderNotFoundErrorResponse } from './EditOrderNotFoundErrorResponse';
import type { GetActivityForbiddenErrorResponse } from './GetActivityForbiddenErrorResponse';
import type { GetActivityNotFoundErrorResponse } from './GetActivityNotFoundErrorResponse';
import type { GetAllocationBadRequestErrorResponse } from './GetAllocationBadRequestErrorResponse';
import type { GetAllocationForbiddenErrorResponse } from './GetAllocationForbiddenErrorResponse';
import type { GetAllocationNotFoundErrorResponse } from './GetAllocationNotFoundErrorResponse';
import type { GetAllocationsByClientNettingIdBadRequestErrorResponse } from './GetAllocationsByClientNettingIdBadRequestErrorResponse';
import type { GetAllocationsByClientNettingIdForbiddenErrorResponse } from './GetAllocationsByClientNettingIdForbiddenErrorResponse';
import type { GetAllocationsByClientNettingIdNotFoundErrorResponse } from './GetAllocationsByClientNettingIdNotFoundErrorResponse';
import type { GetBuyingPowerBadRequestErrorResponse } from './GetBuyingPowerBadRequestErrorResponse';
import type { GetBuyingPowerForbiddenErrorResponse } from './GetBuyingPowerForbiddenErrorResponse';
import type { GetBuyingPowerNotFoundErrorResponse } from './GetBuyingPowerNotFoundErrorResponse';
import type { GetCandlesBadRequestErrorResponse } from './GetCandlesBadRequestErrorResponse';
import type { GetCandlesForbiddenErrorResponse } from './GetCandlesForbiddenErrorResponse';
import type { GetCandlesNotFoundErrorResponse } from './GetCandlesNotFoundErrorResponse';
import type { GetConversionFeesForbiddenErrorResponse } from './GetConversionFeesForbiddenErrorResponse';
import type { GetCrossMarginOverviewBadRequestErrorResponse } from './GetCrossMarginOverviewBadRequestErrorResponse';
import type { GetCrossMarginOverviewForbiddenErrorResponse } from './GetCrossMarginOverviewForbiddenErrorResponse';
import type { GetCrossMarginOverviewNotFoundErrorResponse } from './GetCrossMarginOverviewNotFoundErrorResponse';
import type { GetCrossMarginPrimeOverviewBadRequestErrorResponse } from './GetCrossMarginPrimeOverviewBadRequestErrorResponse';
import type { GetCrossMarginPrimeOverviewForbiddenErrorResponse } from './GetCrossMarginPrimeOverviewForbiddenErrorResponse';
import type { GetCrossMarginPrimeOverviewNotFoundErrorResponse } from './GetCrossMarginPrimeOverviewNotFoundErrorResponse';
import type { GetCrossMarginRiskParametersBadRequestErrorResponse } from './GetCrossMarginRiskParametersBadRequestErrorResponse';
import type { GetCrossMarginRiskParametersForbiddenErrorResponse } from './GetCrossMarginRiskParametersForbiddenErrorResponse';
import type { GetCrossMarginRiskParametersNotFoundErrorResponse } from './GetCrossMarginRiskParametersNotFoundErrorResponse';
import type { GetDerivativePositionsBadRequestErrorResponse } from './GetDerivativePositionsBadRequestErrorResponse';
import type { GetDerivativePositionsForbiddenErrorResponse } from './GetDerivativePositionsForbiddenErrorResponse';
import type { GetDerivativePositionsNotFoundErrorResponse } from './GetDerivativePositionsNotFoundErrorResponse';
import type { GetDerivativesCurrencySummaryBadRequestErrorResponse } from './GetDerivativesCurrencySummaryBadRequestErrorResponse';
import type { GetDerivativesCurrencySummaryForbiddenErrorResponse } from './GetDerivativesCurrencySummaryForbiddenErrorResponse';
import type { GetDerivativesCurrencySummaryNotFoundErrorResponse } from './GetDerivativesCurrencySummaryNotFoundErrorResponse';
import type { GetEntityActivitiesBadRequestErrorResponse } from './GetEntityActivitiesBadRequestErrorResponse';
import type { GetEntityActivitiesForbiddenErrorResponse } from './GetEntityActivitiesForbiddenErrorResponse';
import type { GetEntityActivitiesNotFoundErrorResponse } from './GetEntityActivitiesNotFoundErrorResponse';
import type { GetEntityAssetsBadRequestErrorResponse } from './GetEntityAssetsBadRequestErrorResponse';
import type { GetEntityAssetsForbiddenErrorResponse } from './GetEntityAssetsForbiddenErrorResponse';
import type { GetEntityAssetsNotFoundErrorResponse } from './GetEntityAssetsNotFoundErrorResponse';
import type { GetEntityPaymentMethodDetailsBadRequestErrorResponse } from './GetEntityPaymentMethodDetailsBadRequestErrorResponse';
import type { GetEntityPaymentMethodDetailsForbiddenErrorResponse } from './GetEntityPaymentMethodDetailsForbiddenErrorResponse';
import type { GetEntityPaymentMethodDetailsNotFoundErrorResponse } from './GetEntityPaymentMethodDetailsNotFoundErrorResponse';
import type { GetEntityPaymentMethodsBadRequestErrorResponse } from './GetEntityPaymentMethodsBadRequestErrorResponse';
import type { GetEntityPaymentMethodsForbiddenErrorResponse } from './GetEntityPaymentMethodsForbiddenErrorResponse';
import type { GetEntityPaymentMethodsNotFoundErrorResponse } from './GetEntityPaymentMethodsNotFoundErrorResponse';
import type { GetEntityUsersBadRequestErrorResponse } from './GetEntityUsersBadRequestErrorResponse';
import type { GetEntityUsersForbiddenErrorResponse } from './GetEntityUsersForbiddenErrorResponse';
import type { GetEntityUsersNotFoundErrorResponse } from './GetEntityUsersNotFoundErrorResponse';
import type { GetExistingLocatesBadRequestErrorResponse } from './GetExistingLocatesBadRequestErrorResponse';
import type { GetExistingLocatesForbiddenErrorResponse } from './GetExistingLocatesForbiddenErrorResponse';
import type { GetExistingLocatesNotFoundErrorResponse } from './GetExistingLocatesNotFoundErrorResponse';
import type { GetFcmBalanceBadRequestErrorResponse } from './GetFcmBalanceBadRequestErrorResponse';
import type { GetFcmBalanceForbiddenErrorResponse } from './GetFcmBalanceForbiddenErrorResponse';
import type { GetFcmBalanceNotFoundErrorResponse } from './GetFcmBalanceNotFoundErrorResponse';
import type { GetFcmEquityBadRequestErrorResponse } from './GetFcmEquityBadRequestErrorResponse';
import type { GetFcmEquityForbiddenErrorResponse } from './GetFcmEquityForbiddenErrorResponse';
import type { GetFcmEquityNotFoundErrorResponse } from './GetFcmEquityNotFoundErrorResponse';
import type { GetFcmMarginCallDetailsBadRequestErrorResponse } from './GetFcmMarginCallDetailsBadRequestErrorResponse';
import type { GetFcmMarginCallDetailsForbiddenErrorResponse } from './GetFcmMarginCallDetailsForbiddenErrorResponse';
import type { GetFcmMarginCallDetailsNotFoundErrorResponse } from './GetFcmMarginCallDetailsNotFoundErrorResponse';
import type { GetFcmRiskLimitsBadRequestErrorResponse } from './GetFcmRiskLimitsBadRequestErrorResponse';
import type { GetFcmRiskLimitsForbiddenErrorResponse } from './GetFcmRiskLimitsForbiddenErrorResponse';
import type { GetFcmRiskLimitsNotFoundErrorResponse } from './GetFcmRiskLimitsNotFoundErrorResponse';
import type { GetFcmSettingsBadRequestErrorResponse } from './GetFcmSettingsBadRequestErrorResponse';
import type { GetFcmSettingsForbiddenErrorResponse } from './GetFcmSettingsForbiddenErrorResponse';
import type { GetFcmSettingsNotFoundErrorResponse } from './GetFcmSettingsNotFoundErrorResponse';
import type { GetFuturesSweepsBadRequestErrorResponse } from './GetFuturesSweepsBadRequestErrorResponse';
import type { GetFuturesSweepsForbiddenErrorResponse } from './GetFuturesSweepsForbiddenErrorResponse';
import type { GetFuturesSweepsNotFoundErrorResponse } from './GetFuturesSweepsNotFoundErrorResponse';
import type { GetInterestAccrualsBadRequestErrorResponse } from './GetInterestAccrualsBadRequestErrorResponse';
import type { GetInterestAccrualsForbiddenErrorResponse } from './GetInterestAccrualsForbiddenErrorResponse';
import type { GetInterestAccrualsNotFoundErrorResponse } from './GetInterestAccrualsNotFoundErrorResponse';
import type { GetInvoicesBadRequestErrorResponse } from './GetInvoicesBadRequestErrorResponse';
import type { GetInvoicesForbiddenErrorResponse } from './GetInvoicesForbiddenErrorResponse';
import type { GetInvoicesNotFoundErrorResponse } from './GetInvoicesNotFoundErrorResponse';
import type { GetLocateAvailabilitiesBadRequestErrorResponse } from './GetLocateAvailabilitiesBadRequestErrorResponse';
import type { GetLocateAvailabilitiesForbiddenErrorResponse } from './GetLocateAvailabilitiesForbiddenErrorResponse';
import type { GetLocateAvailabilitiesNotFoundErrorResponse } from './GetLocateAvailabilitiesNotFoundErrorResponse';
import type { GetMarginConversionsBadRequestErrorResponse } from './GetMarginConversionsBadRequestErrorResponse';
import type { GetMarginConversionsForbiddenErrorResponse } from './GetMarginConversionsForbiddenErrorResponse';
import type { GetMarginConversionsNotFoundErrorResponse } from './GetMarginConversionsNotFoundErrorResponse';
import type { GetMarginInformationBadRequestErrorResponse } from './GetMarginInformationBadRequestErrorResponse';
import type { GetMarginInformationForbiddenErrorResponse } from './GetMarginInformationForbiddenErrorResponse';
import type { GetMarginInformationNotFoundErrorResponse } from './GetMarginInformationNotFoundErrorResponse';
import type { GetMarginSummariesBadRequestErrorResponse } from './GetMarginSummariesBadRequestErrorResponse';
import type { GetMarginSummariesForbiddenErrorResponse } from './GetMarginSummariesForbiddenErrorResponse';
import type { GetMarginSummariesNotFoundErrorResponse } from './GetMarginSummariesNotFoundErrorResponse';
import type { GetMarketDataBadRequestErrorResponse } from './GetMarketDataBadRequestErrorResponse';
import type { GetMarketDataForbiddenErrorResponse } from './GetMarketDataForbiddenErrorResponse';
import type { GetMarketDataNotFoundErrorResponse } from './GetMarketDataNotFoundErrorResponse';
import type { GetOpenOrdersBadRequestErrorResponse } from './GetOpenOrdersBadRequestErrorResponse';
import type { GetOpenOrdersForbiddenErrorResponse } from './GetOpenOrdersForbiddenErrorResponse';
import type { GetOpenOrdersNotFoundErrorResponse } from './GetOpenOrdersNotFoundErrorResponse';
import type { GetOrderBadRequestErrorResponse } from './GetOrderBadRequestErrorResponse';
import type { GetOrderEditHistoryBadRequestErrorResponse } from './GetOrderEditHistoryBadRequestErrorResponse';
import type { GetOrderEditHistoryForbiddenErrorResponse } from './GetOrderEditHistoryForbiddenErrorResponse';
import type { GetOrderEditHistoryNotFoundErrorResponse } from './GetOrderEditHistoryNotFoundErrorResponse';
import type { GetOrderFillsBadRequestErrorResponse } from './GetOrderFillsBadRequestErrorResponse';
import type { GetOrderFillsForbiddenErrorResponse } from './GetOrderFillsForbiddenErrorResponse';
import type { GetOrderFillsNotFoundErrorResponse } from './GetOrderFillsNotFoundErrorResponse';
import type { GetOrderForbiddenErrorResponse } from './GetOrderForbiddenErrorResponse';
import type { GetOrderNotFoundErrorResponse } from './GetOrderNotFoundErrorResponse';
import type { GetOrdersBadRequestErrorResponse } from './GetOrdersBadRequestErrorResponse';
import type { GetOrdersForbiddenErrorResponse } from './GetOrdersForbiddenErrorResponse';
import type { GetOrdersNotFoundErrorResponse } from './GetOrdersNotFoundErrorResponse';
import type { GetPortfolioActivitiesBadRequestErrorResponse } from './GetPortfolioActivitiesBadRequestErrorResponse';
import type { GetPortfolioActivitiesForbiddenErrorResponse } from './GetPortfolioActivitiesForbiddenErrorResponse';
import type { GetPortfolioActivitiesNotFoundErrorResponse } from './GetPortfolioActivitiesNotFoundErrorResponse';
import type { GetPortfolioActivityBadRequestErrorResponse } from './GetPortfolioActivityBadRequestErrorResponse';
import type { GetPortfolioActivityForbiddenErrorResponse } from './GetPortfolioActivityForbiddenErrorResponse';
import type { GetPortfolioActivityNotFoundErrorResponse } from './GetPortfolioActivityNotFoundErrorResponse';
import type { GetPortfolioAddressBookBadRequestErrorResponse } from './GetPortfolioAddressBookBadRequestErrorResponse';
import type { GetPortfolioAddressBookForbiddenErrorResponse } from './GetPortfolioAddressBookForbiddenErrorResponse';
import type { GetPortfolioAddressBookNotFoundErrorResponse } from './GetPortfolioAddressBookNotFoundErrorResponse';
import type { GetPortfolioAllocationsBadRequestErrorResponse } from './GetPortfolioAllocationsBadRequestErrorResponse';
import type { GetPortfolioAllocationsForbiddenErrorResponse } from './GetPortfolioAllocationsForbiddenErrorResponse';
import type { GetPortfolioAllocationsNotFoundErrorResponse } from './GetPortfolioAllocationsNotFoundErrorResponse';
import type { GetPortfolioBadRequestErrorResponse } from './GetPortfolioBadRequestErrorResponse';
import type { GetPortfolioBalancesBadRequestErrorResponse } from './GetPortfolioBalancesBadRequestErrorResponse';
import type { GetPortfolioBalancesForbiddenErrorResponse } from './GetPortfolioBalancesForbiddenErrorResponse';
import type { GetPortfolioBalancesNotFoundErrorResponse } from './GetPortfolioBalancesNotFoundErrorResponse';
import type { GetPortfolioCommissionBadRequestErrorResponse } from './GetPortfolioCommissionBadRequestErrorResponse';
import type { GetPortfolioCommissionForbiddenErrorResponse } from './GetPortfolioCommissionForbiddenErrorResponse';
import type { GetPortfolioCommissionNotFoundErrorResponse } from './GetPortfolioCommissionNotFoundErrorResponse';
import type { GetPortfolioCounterpartyIDBadRequestErrorResponse } from './GetPortfolioCounterpartyIDBadRequestErrorResponse';
import type { GetPortfolioCounterpartyIDForbiddenErrorResponse } from './GetPortfolioCounterpartyIDForbiddenErrorResponse';
import type { GetPortfolioCounterpartyIDNotFoundErrorResponse } from './GetPortfolioCounterpartyIDNotFoundErrorResponse';
import type { GetPortfolioFillsBadRequestErrorResponse } from './GetPortfolioFillsBadRequestErrorResponse';
import type { GetPortfolioFillsForbiddenErrorResponse } from './GetPortfolioFillsForbiddenErrorResponse';
import type { GetPortfolioFillsNotFoundErrorResponse } from './GetPortfolioFillsNotFoundErrorResponse';
import type { GetPortfolioForbiddenErrorResponse } from './GetPortfolioForbiddenErrorResponse';
import type { GetPortfolioInterestAccrualsBadRequestErrorResponse } from './GetPortfolioInterestAccrualsBadRequestErrorResponse';
import type { GetPortfolioInterestAccrualsForbiddenErrorResponse } from './GetPortfolioInterestAccrualsForbiddenErrorResponse';
import type { GetPortfolioInterestAccrualsNotFoundErrorResponse } from './GetPortfolioInterestAccrualsNotFoundErrorResponse';
import type { GetPortfolioNotFoundErrorResponse } from './GetPortfolioNotFoundErrorResponse';
import type { GetPortfolioProductsBadRequestErrorResponse } from './GetPortfolioProductsBadRequestErrorResponse';
import type { GetPortfolioProductsForbiddenErrorResponse } from './GetPortfolioProductsForbiddenErrorResponse';
import type { GetPortfolioProductsNotFoundErrorResponse } from './GetPortfolioProductsNotFoundErrorResponse';
import type { GetPortfolioTransactionsBadRequestErrorResponse } from './GetPortfolioTransactionsBadRequestErrorResponse';
import type { GetPortfolioTransactionsForbiddenErrorResponse } from './GetPortfolioTransactionsForbiddenErrorResponse';
import type { GetPortfolioTransactionsNotFoundErrorResponse } from './GetPortfolioTransactionsNotFoundErrorResponse';
import type { GetPortfolioUsersBadRequestErrorResponse } from './GetPortfolioUsersBadRequestErrorResponse';
import type { GetPortfolioUsersForbiddenErrorResponse } from './GetPortfolioUsersForbiddenErrorResponse';
import type { GetPortfolioUsersNotFoundErrorResponse } from './GetPortfolioUsersNotFoundErrorResponse';
import type { GetPortfoliosForbiddenErrorResponse } from './GetPortfoliosForbiddenErrorResponse';
import type { GetPortfoliosNotFoundErrorResponse } from './GetPortfoliosNotFoundErrorResponse';
import type { GetPositionsBadRequestErrorResponse } from './GetPositionsBadRequestErrorResponse';
import type { GetPositionsForbiddenErrorResponse } from './GetPositionsForbiddenErrorResponse';
import type { GetPositionsNotFoundErrorResponse } from './GetPositionsNotFoundErrorResponse';
import type { GetPostTradeCreditBadRequestErrorResponse } from './GetPostTradeCreditBadRequestErrorResponse';
import type { GetPostTradeCreditForbiddenErrorResponse } from './GetPostTradeCreditForbiddenErrorResponse';
import type { GetPostTradeCreditNotFoundErrorResponse } from './GetPostTradeCreditNotFoundErrorResponse';
import type { GetStakingStatusBadRequestErrorResponse } from './GetStakingStatusBadRequestErrorResponse';
import type { GetStakingStatusForbiddenErrorResponse } from './GetStakingStatusForbiddenErrorResponse';
import type { GetStakingStatusNotFoundErrorResponse } from './GetStakingStatusNotFoundErrorResponse';
import type { GetTFTieredPricingFeesBadRequestErrorResponse } from './GetTFTieredPricingFeesBadRequestErrorResponse';
import type { GetTFTieredPricingFeesForbiddenErrorResponse } from './GetTFTieredPricingFeesForbiddenErrorResponse';
import type { GetTFTieredPricingFeesNotFoundErrorResponse } from './GetTFTieredPricingFeesNotFoundErrorResponse';
import type { GetTransactionBadRequestErrorResponse } from './GetTransactionBadRequestErrorResponse';
import type { GetTransactionForbiddenErrorResponse } from './GetTransactionForbiddenErrorResponse';
import type { GetTransactionNotFoundErrorResponse } from './GetTransactionNotFoundErrorResponse';
import type { GetTransactionTravelRuleDataBadRequestErrorResponse } from './GetTransactionTravelRuleDataBadRequestErrorResponse';
import type { GetTransactionTravelRuleDataForbiddenErrorResponse } from './GetTransactionTravelRuleDataForbiddenErrorResponse';
import type { GetTransactionTravelRuleDataNotFoundErrorResponse } from './GetTransactionTravelRuleDataNotFoundErrorResponse';
import type { GetUnstakingStatusBadRequestErrorResponse } from './GetUnstakingStatusBadRequestErrorResponse';
import type { GetUnstakingStatusForbiddenErrorResponse } from './GetUnstakingStatusForbiddenErrorResponse';
import type { GetUnstakingStatusNotFoundErrorResponse } from './GetUnstakingStatusNotFoundErrorResponse';
import type { GetWalletBadRequestErrorResponse } from './GetWalletBadRequestErrorResponse';
import type { GetWalletBalanceBadRequestErrorResponse } from './GetWalletBalanceBadRequestErrorResponse';
import type { GetWalletBalanceForbiddenErrorResponse } from './GetWalletBalanceForbiddenErrorResponse';
import type { GetWalletBalanceNotFoundErrorResponse } from './GetWalletBalanceNotFoundErrorResponse';
import type { GetWalletDepositInstructionsBadRequestErrorResponse } from './GetWalletDepositInstructionsBadRequestErrorResponse';
import type { GetWalletDepositInstructionsForbiddenErrorResponse } from './GetWalletDepositInstructionsForbiddenErrorResponse';
import type { GetWalletDepositInstructionsNotFoundErrorResponse } from './GetWalletDepositInstructionsNotFoundErrorResponse';
import type { GetWalletForbiddenErrorResponse } from './GetWalletForbiddenErrorResponse';
import type { GetWalletNotFoundErrorResponse } from './GetWalletNotFoundErrorResponse';
import type { GetWalletTransactionsBadRequestErrorResponse } from './GetWalletTransactionsBadRequestErrorResponse';
import type { GetWalletTransactionsForbiddenErrorResponse } from './GetWalletTransactionsForbiddenErrorResponse';
import type { GetWalletTransactionsNotFoundErrorResponse } from './GetWalletTransactionsNotFoundErrorResponse';
import type { GetWalletsBadRequestErrorResponse } from './GetWalletsBadRequestErrorResponse';
import type { GetWalletsForbiddenErrorResponse } from './GetWalletsForbiddenErrorResponse';
import type { GetWalletsNotFoundErrorResponse } from './GetWalletsNotFoundErrorResponse';
import type { GetWithdrawalPowerBadRequestErrorResponse } from './GetWithdrawalPowerBadRequestErrorResponse';
import type { GetWithdrawalPowerForbiddenErrorResponse } from './GetWithdrawalPowerForbiddenErrorResponse';
import type { GetWithdrawalPowerNotFoundErrorResponse } from './GetWithdrawalPowerNotFoundErrorResponse';
import type { GetXMLiquidationBadRequestErrorResponse } from './GetXMLiquidationBadRequestErrorResponse';
import type { GetXMLiquidationForbiddenErrorResponse } from './GetXMLiquidationForbiddenErrorResponse';
import type { GetXMLiquidationNotFoundErrorResponse } from './GetXMLiquidationNotFoundErrorResponse';
import type { InternalServerErrorResponse } from './InternalServerErrorResponse';
import type { ListAdvancedTransferTransactionsForbiddenErrorResponse } from './ListAdvancedTransferTransactionsForbiddenErrorResponse';
import type { ListAdvancedTransferTransactionsNotFoundErrorResponse } from './ListAdvancedTransferTransactionsNotFoundErrorResponse';
import type { ListAdvancedTransfersBadRequestErrorResponse } from './ListAdvancedTransfersBadRequestErrorResponse';
import type { ListAdvancedTransfersForbiddenErrorResponse } from './ListAdvancedTransfersForbiddenErrorResponse';
import type { ListAdvancedTransfersNotFoundErrorResponse } from './ListAdvancedTransfersNotFoundErrorResponse';
import type { ListAggregateEntityPositionsBadRequestErrorResponse } from './ListAggregateEntityPositionsBadRequestErrorResponse';
import type { ListAggregateEntityPositionsForbiddenErrorResponse } from './ListAggregateEntityPositionsForbiddenErrorResponse';
import type { ListAggregateEntityPositionsNotFoundErrorResponse } from './ListAggregateEntityPositionsNotFoundErrorResponse';
import type { ListEntityBalancesBadRequestErrorResponse } from './ListEntityBalancesBadRequestErrorResponse';
import type { ListEntityBalancesForbiddenErrorResponse } from './ListEntityBalancesForbiddenErrorResponse';
import type { ListEntityBalancesNotFoundErrorResponse } from './ListEntityBalancesNotFoundErrorResponse';
import type { ListEntityPositionsBadRequestErrorResponse } from './ListEntityPositionsBadRequestErrorResponse';
import type { ListEntityPositionsForbiddenErrorResponse } from './ListEntityPositionsForbiddenErrorResponse';
import type { ListEntityPositionsNotFoundErrorResponse } from './ListEntityPositionsNotFoundErrorResponse';
import type { ListOnchainAddressGroupsBadRequestErrorResponse } from './ListOnchainAddressGroupsBadRequestErrorResponse';
import type { ListOnchainAddressGroupsForbiddenErrorResponse } from './ListOnchainAddressGroupsForbiddenErrorResponse';
import type { ListOnchainAddressGroupsNotFoundErrorResponse } from './ListOnchainAddressGroupsNotFoundErrorResponse';
import type { ListTFObligationsBadRequestErrorResponse } from './ListTFObligationsBadRequestErrorResponse';
import type { ListTFObligationsForbiddenErrorResponse } from './ListTFObligationsForbiddenErrorResponse';
import type { ListTFObligationsNotFoundErrorResponse } from './ListTFObligationsNotFoundErrorResponse';
import type { ListTransactionValidatorsBadRequestErrorResponse } from './ListTransactionValidatorsBadRequestErrorResponse';
import type { ListTransactionValidatorsForbiddenErrorResponse } from './ListTransactionValidatorsForbiddenErrorResponse';
import type { ListTransactionValidatorsNotFoundErrorResponse } from './ListTransactionValidatorsNotFoundErrorResponse';
import type { ListWalletAddressesBadRequestErrorResponse } from './ListWalletAddressesBadRequestErrorResponse';
import type { ListWalletAddressesForbiddenErrorResponse } from './ListWalletAddressesForbiddenErrorResponse';
import type { ListWalletAddressesNotFoundErrorResponse } from './ListWalletAddressesNotFoundErrorResponse';
import type { ListWeb3WalletBalancesBadRequestErrorResponse } from './ListWeb3WalletBalancesBadRequestErrorResponse';
import type { ListWeb3WalletBalancesForbiddenErrorResponse } from './ListWeb3WalletBalancesForbiddenErrorResponse';
import type { ListWeb3WalletBalancesNotFoundErrorResponse } from './ListWeb3WalletBalancesNotFoundErrorResponse';
import type { ListXMLiquidationsBadRequestErrorResponse } from './ListXMLiquidationsBadRequestErrorResponse';
import type { ListXMLiquidationsForbiddenErrorResponse } from './ListXMLiquidationsForbiddenErrorResponse';
import type { ListXMLiquidationsNotFoundErrorResponse } from './ListXMLiquidationsNotFoundErrorResponse';
import type { NotImplementedErrorResponse } from './NotImplementedErrorResponse';
import type { OrderPreviewBadRequestErrorResponse } from './OrderPreviewBadRequestErrorResponse';
import type { OrderPreviewForbiddenErrorResponse } from './OrderPreviewForbiddenErrorResponse';
import type { OrderPreviewNotFoundErrorResponse } from './OrderPreviewNotFoundErrorResponse';
import type { PortfolioStakingInitiateBadRequestErrorResponse } from './PortfolioStakingInitiateBadRequestErrorResponse';
import type { PortfolioStakingInitiateForbiddenErrorResponse } from './PortfolioStakingInitiateForbiddenErrorResponse';
import type { PortfolioStakingInitiateNotFoundErrorResponse } from './PortfolioStakingInitiateNotFoundErrorResponse';
import type { PortfolioStakingUnstakeBadRequestErrorResponse } from './PortfolioStakingUnstakeBadRequestErrorResponse';
import type { PortfolioStakingUnstakeForbiddenErrorResponse } from './PortfolioStakingUnstakeForbiddenErrorResponse';
import type { PortfolioStakingUnstakeNotFoundErrorResponse } from './PortfolioStakingUnstakeNotFoundErrorResponse';
import type { PreviewUnstakeBadRequestErrorResponse } from './PreviewUnstakeBadRequestErrorResponse';
import type { PreviewUnstakeForbiddenErrorResponse } from './PreviewUnstakeForbiddenErrorResponse';
import type { RotateAPIKeyBadRequestErrorResponse } from './RotateAPIKeyBadRequestErrorResponse';
import type { RotateAPIKeyForbiddenErrorResponse } from './RotateAPIKeyForbiddenErrorResponse';
import type { ScheduleFuturesSweepBadRequestErrorResponse } from './ScheduleFuturesSweepBadRequestErrorResponse';
import type { ScheduleFuturesSweepForbiddenErrorResponse } from './ScheduleFuturesSweepForbiddenErrorResponse';
import type { ScheduleFuturesSweepNotFoundErrorResponse } from './ScheduleFuturesSweepNotFoundErrorResponse';
import type { ServiceUnavailableErrorResponse } from './ServiceUnavailableErrorResponse';
import type { SetAutoSweepBadRequestErrorResponse } from './SetAutoSweepBadRequestErrorResponse';
import type { SetAutoSweepForbiddenErrorResponse } from './SetAutoSweepForbiddenErrorResponse';
import type { SetAutoSweepNotFoundErrorResponse } from './SetAutoSweepNotFoundErrorResponse';
import type { SetFcmSettingsBadRequestErrorResponse } from './SetFcmSettingsBadRequestErrorResponse';
import type { SetFcmSettingsForbiddenErrorResponse } from './SetFcmSettingsForbiddenErrorResponse';
import type { SetFcmSettingsNotFoundErrorResponse } from './SetFcmSettingsNotFoundErrorResponse';
import type { StakingClaimRewardsBadRequestErrorResponse } from './StakingClaimRewardsBadRequestErrorResponse';
import type { StakingClaimRewardsForbiddenErrorResponse } from './StakingClaimRewardsForbiddenErrorResponse';
import type { StakingClaimRewardsNotFoundErrorResponse } from './StakingClaimRewardsNotFoundErrorResponse';
import type { StakingInitiateBadRequestErrorResponse } from './StakingInitiateBadRequestErrorResponse';
import type { StakingInitiateForbiddenErrorResponse } from './StakingInitiateForbiddenErrorResponse';
import type { StakingInitiateNotFoundErrorResponse } from './StakingInitiateNotFoundErrorResponse';
import type { StakingUnstakeBadRequestErrorResponse } from './StakingUnstakeBadRequestErrorResponse';
import type { StakingUnstakeForbiddenErrorResponse } from './StakingUnstakeForbiddenErrorResponse';
import type { StakingUnstakeNotFoundErrorResponse } from './StakingUnstakeNotFoundErrorResponse';
import type { SubmitDepositTravelRuleDataBadRequestErrorResponse } from './SubmitDepositTravelRuleDataBadRequestErrorResponse';
import type { SubmitDepositTravelRuleDataForbiddenErrorResponse } from './SubmitDepositTravelRuleDataForbiddenErrorResponse';
import type { SubmitDepositTravelRuleDataNotFoundErrorResponse } from './SubmitDepositTravelRuleDataNotFoundErrorResponse';
import type { TooManyRequestsErrorResponse } from './TooManyRequestsErrorResponse';
import type { UnauthorizedErrorResponse } from './UnauthorizedErrorResponse';
import type { UpdateFundingSettingsBadRequestErrorResponse } from './UpdateFundingSettingsBadRequestErrorResponse';
import type { UpdateFundingSettingsForbiddenErrorResponse } from './UpdateFundingSettingsForbiddenErrorResponse';
import type { UpdateFundingSettingsNotFoundErrorResponse } from './UpdateFundingSettingsNotFoundErrorResponse';
import type { UpdateOnchainAddressGroupBadRequestErrorResponse } from './UpdateOnchainAddressGroupBadRequestErrorResponse';
import type { UpdateOnchainAddressGroupForbiddenErrorResponse } from './UpdateOnchainAddressGroupForbiddenErrorResponse';
import type { UpdateOnchainAddressGroupNotFoundErrorResponse } from './UpdateOnchainAddressGroupNotFoundErrorResponse';

export type AcceptQuoteError =
  | AcceptQuoteBadRequestErrorResponse
  | AcceptQuoteForbiddenErrorResponse
  | AcceptQuoteNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CancelAdvancedTransferError =
  | CancelAdvancedTransferBadRequestErrorResponse
  | CancelAdvancedTransferForbiddenErrorResponse
  | CancelAdvancedTransferNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CancelEntitySweepError =
  | CancelFuturesSweepBadRequestErrorResponse
  | CancelFuturesSweepForbiddenErrorResponse
  | CancelFuturesSweepNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CancelOrderError =
  | CancelOrderBadRequestErrorResponse
  | CancelOrderForbiddenErrorResponse
  | CancelOrderNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ClaimRewardsError =
  | ServiceUnavailableErrorResponse
  | StakingClaimRewardsBadRequestErrorResponse
  | StakingClaimRewardsForbiddenErrorResponse
  | StakingClaimRewardsNotFoundErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateAddressBookError =
  | CreatePortfolioAddressBookEntryBadRequestErrorResponse
  | CreatePortfolioAddressBookEntryForbiddenErrorResponse
  | CreatePortfolioAddressBookEntryNotFoundErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateAdvancedTransferError =
  | CreateAdvancedTransferBadRequestErrorResponse
  | CreateAdvancedTransferForbiddenErrorResponse
  | CreateAdvancedTransferNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateAllocationError =
  | CreateAllocationBadRequestErrorResponse
  | CreateAllocationForbiddenErrorResponse
  | CreateAllocationNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateConversionError =
  | CreateConversionBadRequestErrorResponse
  | CreateConversionForbiddenErrorResponse
  | CreateConversionNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateNetAllocationError =
  | CreateNetAllocationBadRequestErrorResponse
  | CreateNetAllocationForbiddenErrorResponse
  | CreateNetAllocationNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateNewLocatesError =
  | GetExistingLocatesBadRequestErrorResponse
  | GetExistingLocatesForbiddenErrorResponse
  | GetExistingLocatesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateOnchainAddressBookEntryError =
  | CreateOnchainAddressGroupBadRequestErrorResponse
  | CreateOnchainAddressGroupForbiddenErrorResponse
  | CreateOnchainAddressGroupNotFoundErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateOnchainTransactionError =
  | CreateOnchainTransactionBadRequestErrorResponse
  | CreateOnchainTransactionForbiddenErrorResponse
  | CreateOnchainTransactionNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateOrderError =
  | CreateOrderBadRequestErrorResponse
  | CreateOrderForbiddenErrorResponse
  | CreateOrderNotFoundErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateOrderPreviewError =
  | InternalServerErrorResponse
  | OrderPreviewBadRequestErrorResponse
  | OrderPreviewForbiddenErrorResponse
  | OrderPreviewNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreatePortfolioStakeError =
  | PortfolioStakingInitiateBadRequestErrorResponse
  | PortfolioStakingInitiateForbiddenErrorResponse
  | PortfolioStakingInitiateNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreatePortfolioUnstakeError =
  | PortfolioStakingUnstakeBadRequestErrorResponse
  | PortfolioStakingUnstakeForbiddenErrorResponse
  | PortfolioStakingUnstakeNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateQuoteError =
  | CreateQuoteRequestBadRequestErrorResponse
  | CreateQuoteRequestForbiddenErrorResponse
  | CreateQuoteRequestNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateStakeError =
  | ServiceUnavailableErrorResponse
  | StakingInitiateBadRequestErrorResponse
  | StakingInitiateForbiddenErrorResponse
  | StakingInitiateNotFoundErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateTransferError =
  | CreateWalletTransferBadRequestErrorResponse
  | CreateWalletTransferForbiddenErrorResponse
  | CreateWalletTransferNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateUnstakeError =
  | ServiceUnavailableErrorResponse
  | StakingUnstakeBadRequestErrorResponse
  | StakingUnstakeForbiddenErrorResponse
  | StakingUnstakeNotFoundErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateWalletDepositAddressError =
  | CreateWalletDepositAddressBadRequestErrorResponse
  | CreateWalletDepositAddressForbiddenErrorResponse
  | CreateWalletDepositAddressNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type CreateWalletError =
  | CreateWalletBadRequestErrorResponse
  | CreateWalletForbiddenErrorResponse
  | CreateWalletNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type CreateWithdrawalError =
  | CreateWalletWithdrawalBadRequestErrorResponse
  | CreateWalletWithdrawalForbiddenErrorResponse
  | CreateWalletWithdrawalNotFoundErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type DeleteOnchainAddressBookError =
  | DeleteOnchainAddressGroupBadRequestErrorResponse
  | DeleteOnchainAddressGroupForbiddenErrorResponse
  | DeleteOnchainAddressGroupNotFoundErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type EditOrderError =
  | EditOrderBadRequestErrorResponse
  | EditOrderForbiddenErrorResponse
  | EditOrderNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetActivityError =
  | GetActivityForbiddenErrorResponse
  | GetActivityNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetAllocationError =
  | GetAllocationBadRequestErrorResponse
  | GetAllocationForbiddenErrorResponse
  | GetAllocationNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetConversionFeesError =
  | GetConversionFeesForbiddenErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetCounterpartyIdError =
  | GetPortfolioCounterpartyIDBadRequestErrorResponse
  | GetPortfolioCounterpartyIDForbiddenErrorResponse
  | GetPortfolioCounterpartyIDNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetCrossMarginLiquidationError =
  | GetXMLiquidationBadRequestErrorResponse
  | GetXMLiquidationForbiddenErrorResponse
  | GetXMLiquidationNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetCrossMarginOverviewError =
  | GetCrossMarginOverviewBadRequestErrorResponse
  | GetCrossMarginOverviewForbiddenErrorResponse
  | GetCrossMarginOverviewNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetCrossMarginPrimeOverviewError =
  | GetCrossMarginPrimeOverviewBadRequestErrorResponse
  | GetCrossMarginPrimeOverviewForbiddenErrorResponse
  | GetCrossMarginPrimeOverviewNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetCrossMarginRiskParametersError =
  | GetCrossMarginRiskParametersBadRequestErrorResponse
  | GetCrossMarginRiskParametersForbiddenErrorResponse
  | GetCrossMarginRiskParametersNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetDerivativesCurrencySummaryError =
  | GetDerivativesCurrencySummaryBadRequestErrorResponse
  | GetDerivativesCurrencySummaryForbiddenErrorResponse
  | GetDerivativesCurrencySummaryNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetEntityBalanceError =
  | GetFcmBalanceBadRequestErrorResponse
  | GetFcmBalanceForbiddenErrorResponse
  | GetFcmBalanceNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetEntityEquityError =
  | GetFcmEquityBadRequestErrorResponse
  | GetFcmEquityForbiddenErrorResponse
  | GetFcmEquityNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetEntityLocateAvailabilitiesError =
  | GetLocateAvailabilitiesBadRequestErrorResponse
  | GetLocateAvailabilitiesForbiddenErrorResponse
  | GetLocateAvailabilitiesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetEntityPositionsError =
  | GetPositionsBadRequestErrorResponse
  | GetPositionsForbiddenErrorResponse
  | GetPositionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetFcmMarginCallDetailsError =
  | GetFcmMarginCallDetailsBadRequestErrorResponse
  | GetFcmMarginCallDetailsForbiddenErrorResponse
  | GetFcmMarginCallDetailsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetFcmRiskLimitsError =
  | GetFcmRiskLimitsBadRequestErrorResponse
  | GetFcmRiskLimitsForbiddenErrorResponse
  | GetFcmRiskLimitsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetFcmSettingsError =
  | GetFcmSettingsBadRequestErrorResponse
  | GetFcmSettingsForbiddenErrorResponse
  | GetFcmSettingsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetMarginCallDetailsError =
  | GetFcmMarginCallDetailsBadRequestErrorResponse
  | GetFcmMarginCallDetailsForbiddenErrorResponse
  | GetFcmMarginCallDetailsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetMarginInformationError =
  | GetMarginInformationBadRequestErrorResponse
  | GetMarginInformationForbiddenErrorResponse
  | GetMarginInformationNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetOrderEditHistoryError =
  | GetOrderEditHistoryBadRequestErrorResponse
  | GetOrderEditHistoryForbiddenErrorResponse
  | GetOrderEditHistoryNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetOrderError =
  | GetOrderBadRequestErrorResponse
  | GetOrderForbiddenErrorResponse
  | GetOrderNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetPaymentMethodError =
  | GetEntityPaymentMethodDetailsBadRequestErrorResponse
  | GetEntityPaymentMethodDetailsForbiddenErrorResponse
  | GetEntityPaymentMethodDetailsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetPortfolioActivityError =
  | GetPortfolioActivityBadRequestErrorResponse
  | GetPortfolioActivityForbiddenErrorResponse
  | GetPortfolioActivityNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetPortfolioBuyingPowerError =
  | GetBuyingPowerBadRequestErrorResponse
  | GetBuyingPowerForbiddenErrorResponse
  | GetBuyingPowerNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetPortfolioCommissionError =
  | GetPortfolioCommissionBadRequestErrorResponse
  | GetPortfolioCommissionForbiddenErrorResponse
  | GetPortfolioCommissionNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetPortfolioCreditError =
  | GetPostTradeCreditBadRequestErrorResponse
  | GetPostTradeCreditForbiddenErrorResponse
  | GetPostTradeCreditNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetPortfolioCreditInformationError =
  | GetPostTradeCreditBadRequestErrorResponse
  | GetPostTradeCreditForbiddenErrorResponse
  | GetPostTradeCreditNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetPortfolioError =
  | GetPortfolioBadRequestErrorResponse
  | GetPortfolioForbiddenErrorResponse
  | GetPortfolioNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetPortfolioWithdrawalPowerError =
  | GetWithdrawalPowerBadRequestErrorResponse
  | GetWithdrawalPowerForbiddenErrorResponse
  | GetWithdrawalPowerNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetRiskLimitsError =
  | GetFcmRiskLimitsBadRequestErrorResponse
  | GetFcmRiskLimitsForbiddenErrorResponse
  | GetFcmRiskLimitsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetStakingStatusError =
  | GetStakingStatusBadRequestErrorResponse
  | GetStakingStatusForbiddenErrorResponse
  | GetStakingStatusNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetTieredPricingFeesError =
  | GetTFTieredPricingFeesBadRequestErrorResponse
  | GetTFTieredPricingFeesForbiddenErrorResponse
  | GetTFTieredPricingFeesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetTransactionError =
  | GetTransactionBadRequestErrorResponse
  | GetTransactionForbiddenErrorResponse
  | GetTransactionNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetTransactionTravelRuleDataError =
  | GetTransactionTravelRuleDataBadRequestErrorResponse
  | GetTransactionTravelRuleDataForbiddenErrorResponse
  | GetTransactionTravelRuleDataNotFoundErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetUnstakingStatusError =
  | GetUnstakingStatusBadRequestErrorResponse
  | GetUnstakingStatusForbiddenErrorResponse
  | GetUnstakingStatusNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type GetWalletBalanceError =
  | GetWalletBalanceBadRequestErrorResponse
  | GetWalletBalanceForbiddenErrorResponse
  | GetWalletBalanceNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetWalletDepositInstructionsError =
  | GetWalletDepositInstructionsBadRequestErrorResponse
  | GetWalletDepositInstructionsForbiddenErrorResponse
  | GetWalletDepositInstructionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type GetWalletError =
  | GetWalletBadRequestErrorResponse
  | GetWalletForbiddenErrorResponse
  | GetWalletNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListAddressBooksError =
  | GetPortfolioAddressBookBadRequestErrorResponse
  | GetPortfolioAddressBookForbiddenErrorResponse
  | GetPortfolioAddressBookNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListAdvancedTransfersError =
  | ListAdvancedTransfersBadRequestErrorResponse
  | ListAdvancedTransfersForbiddenErrorResponse
  | ListAdvancedTransfersNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListAdvancedTransferTransactionsError =
  | ListAdvancedTransferTransactionsForbiddenErrorResponse
  | ListAdvancedTransferTransactionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListAggregateEntityPositionsError =
  | ListAggregateEntityPositionsBadRequestErrorResponse
  | ListAggregateEntityPositionsForbiddenErrorResponse
  | ListAggregateEntityPositionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListAssetsError =
  | GetEntityAssetsBadRequestErrorResponse
  | GetEntityAssetsForbiddenErrorResponse
  | GetEntityAssetsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListCrossMarginLiquidationsError =
  | ListXMLiquidationsBadRequestErrorResponse
  | ListXMLiquidationsForbiddenErrorResponse
  | ListXMLiquidationsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListDerivativePositionsError =
  | GetDerivativePositionsBadRequestErrorResponse
  | GetDerivativePositionsForbiddenErrorResponse
  | GetDerivativePositionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListEntityActivitiesError =
  | GetEntityActivitiesBadRequestErrorResponse
  | GetEntityActivitiesForbiddenErrorResponse
  | GetEntityActivitiesNotFoundErrorResponse
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListEntityBalancesError =
  | ListEntityBalancesBadRequestErrorResponse
  | ListEntityBalancesForbiddenErrorResponse
  | ListEntityBalancesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListEntityPaymentMethodsError =
  | GetEntityPaymentMethodsBadRequestErrorResponse
  | GetEntityPaymentMethodsForbiddenErrorResponse
  | GetEntityPaymentMethodsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListEntityPositionsError =
  | ListEntityPositionsBadRequestErrorResponse
  | ListEntityPositionsForbiddenErrorResponse
  | ListEntityPositionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListEntitySweepsError =
  | GetFuturesSweepsBadRequestErrorResponse
  | GetFuturesSweepsForbiddenErrorResponse
  | GetFuturesSweepsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListExistingLocatesError =
  | GetExistingLocatesBadRequestErrorResponse
  | GetExistingLocatesForbiddenErrorResponse
  | GetExistingLocatesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListInterestAccrualsError =
  | GetInterestAccrualsBadRequestErrorResponse
  | GetInterestAccrualsForbiddenErrorResponse
  | GetInterestAccrualsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListInvoicesError =
  | GetInvoicesBadRequestErrorResponse
  | GetInvoicesForbiddenErrorResponse
  | GetInvoicesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListMarginCallSummariesError =
  | GetMarginSummariesBadRequestErrorResponse
  | GetMarginSummariesForbiddenErrorResponse
  | GetMarginSummariesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListMarginConversionsError =
  | GetMarginConversionsBadRequestErrorResponse
  | GetMarginConversionsForbiddenErrorResponse
  | GetMarginConversionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListMarketDataError =
  | GetMarketDataBadRequestErrorResponse
  | GetMarketDataForbiddenErrorResponse
  | GetMarketDataNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListNetAllocationsError =
  | GetAllocationsByClientNettingIdBadRequestErrorResponse
  | GetAllocationsByClientNettingIdForbiddenErrorResponse
  | GetAllocationsByClientNettingIdNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListOnchainAddressBookError =
  | InternalServerErrorResponse
  | ListOnchainAddressGroupsBadRequestErrorResponse
  | ListOnchainAddressGroupsForbiddenErrorResponse
  | ListOnchainAddressGroupsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListOnchainWalletBalancesError =
  | ListWeb3WalletBalancesBadRequestErrorResponse
  | ListWeb3WalletBalancesForbiddenErrorResponse
  | ListWeb3WalletBalancesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListOpenOrdersError =
  | GetOpenOrdersBadRequestErrorResponse
  | GetOpenOrdersForbiddenErrorResponse
  | GetOpenOrdersNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListOrderFillsError =
  | GetOrderFillsBadRequestErrorResponse
  | GetOrderFillsForbiddenErrorResponse
  | GetOrderFillsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListPortfolioActivitiesError =
  | GetPortfolioActivitiesBadRequestErrorResponse
  | GetPortfolioActivitiesForbiddenErrorResponse
  | GetPortfolioActivitiesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListPortfolioAllocationsError =
  | GetPortfolioAllocationsBadRequestErrorResponse
  | GetPortfolioAllocationsForbiddenErrorResponse
  | GetPortfolioAllocationsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListPortfolioBalancesError =
  | GetPortfolioBalancesBadRequestErrorResponse
  | GetPortfolioBalancesForbiddenErrorResponse
  | GetPortfolioBalancesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListPortfolioFillsError =
  | GetPortfolioFillsBadRequestErrorResponse
  | GetPortfolioFillsForbiddenErrorResponse
  | GetPortfolioFillsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListPortfolioInterestAccrualsError =
  | GetPortfolioInterestAccrualsBadRequestErrorResponse
  | GetPortfolioInterestAccrualsForbiddenErrorResponse
  | GetPortfolioInterestAccrualsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListPortfolioOrdersError =
  | GetOrdersBadRequestErrorResponse
  | GetOrdersForbiddenErrorResponse
  | GetOrdersNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListPortfoliosError =
  | GetPortfoliosForbiddenErrorResponse
  | GetPortfoliosNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListPortfolioTransactionsError =
  | GetPortfolioTransactionsBadRequestErrorResponse
  | GetPortfolioTransactionsForbiddenErrorResponse
  | GetPortfolioTransactionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListPortfolioUsersError =
  | GetPortfolioUsersBadRequestErrorResponse
  | GetPortfolioUsersForbiddenErrorResponse
  | GetPortfolioUsersNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListProductCandlesError =
  | GetCandlesBadRequestErrorResponse
  | GetCandlesForbiddenErrorResponse
  | GetCandlesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListProductsError =
  | GetPortfolioProductsBadRequestErrorResponse
  | GetPortfolioProductsForbiddenErrorResponse
  | GetPortfolioProductsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListTFObligationsError =
  | ListTFObligationsBadRequestErrorResponse
  | ListTFObligationsForbiddenErrorResponse
  | ListTFObligationsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListUsersError =
  | GetEntityUsersBadRequestErrorResponse
  | GetEntityUsersForbiddenErrorResponse
  | GetEntityUsersNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ListWalletAddressesError =
  | ListWalletAddressesBadRequestErrorResponse
  | ListWalletAddressesForbiddenErrorResponse
  | ListWalletAddressesNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListWalletsError =
  | GetWalletsBadRequestErrorResponse
  | GetWalletsForbiddenErrorResponse
  | GetWalletsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type ListWalletTransactionsError =
  | GetWalletTransactionsBadRequestErrorResponse
  | GetWalletTransactionsForbiddenErrorResponse
  | GetWalletTransactionsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type PreviewUnstakeError =
  | PreviewUnstakeBadRequestErrorResponse
  | PreviewUnstakeForbiddenErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type QueryTransactionValidatorsError =
  | ListTransactionValidatorsBadRequestErrorResponse
  | ListTransactionValidatorsForbiddenErrorResponse
  | ListTransactionValidatorsNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse;

export type RotateApiKeyError =
  | InternalServerErrorResponse
  | NotImplementedErrorResponse
  | RotateAPIKeyBadRequestErrorResponse
  | RotateAPIKeyForbiddenErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type ScheduleEntitySweepError =
  | ScheduleFuturesSweepBadRequestErrorResponse
  | ScheduleFuturesSweepForbiddenErrorResponse
  | ScheduleFuturesSweepNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type SetFcmSettingsError =
  | ServiceUnavailableErrorResponse
  | SetFcmSettingsBadRequestErrorResponse
  | SetFcmSettingsForbiddenErrorResponse
  | SetFcmSettingsNotFoundErrorResponse
  | TooManyRequestsErrorResponse;

export type SetFundingSettingsError =
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UnauthorizedErrorResponse
  | UpdateFundingSettingsBadRequestErrorResponse
  | UpdateFundingSettingsForbiddenErrorResponse
  | UpdateFundingSettingsNotFoundErrorResponse;

export type SubmitDepositTravelRuleError =
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | SubmitDepositTravelRuleDataBadRequestErrorResponse
  | SubmitDepositTravelRuleDataForbiddenErrorResponse
  | SubmitDepositTravelRuleDataNotFoundErrorResponse
  | TooManyRequestsErrorResponse;

export type UpdateEntityAutoSweepError =
  | ServiceUnavailableErrorResponse
  | SetAutoSweepBadRequestErrorResponse
  | SetAutoSweepForbiddenErrorResponse
  | SetAutoSweepNotFoundErrorResponse
  | TooManyRequestsErrorResponse;

export type UpdateFundingSettingsError =
  | GetXMLiquidationBadRequestErrorResponse
  | GetXMLiquidationForbiddenErrorResponse
  | GetXMLiquidationNotFoundErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse;

export type UpdateOnchainAddressBookEntryError =
  | InternalServerErrorResponse
  | ServiceUnavailableErrorResponse
  | TooManyRequestsErrorResponse
  | UpdateOnchainAddressGroupBadRequestErrorResponse
  | UpdateOnchainAddressGroupForbiddenErrorResponse
  | UpdateOnchainAddressGroupNotFoundErrorResponse;
