/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum AcceptQuoteBadRequestSubcode {
  /**
   * The entity_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The requested currency pair is not valid or not supported for buying power.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  BuyingPowerCurrencyInvalid = 'BUYING_POWER_CURRENCY_INVALID',
  /**
   * The buying power request failed a precondition, such as the portfolio not being in a state that supports the requested currency pair.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  BuyingPowerFailedPrecondition = 'BUYING_POWER_FAILED_PRECONDITION',
  /**
   * The order request failed validation, such as an invalid stp_id, price, size, or commission_rate.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderRequestInvalid = 'ORDER_REQUEST_INVALID',
  /**
   * An order with this client_order_id already exists. Use a unique client_order_id for each new order.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderDuplicateClientOrderId = 'ORDER_DUPLICATE_CLIENT_ORDER_ID',
  /**
   * The order was rejected during processing and was not placed.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderRejected = 'ORDER_REJECTED',
  /**
   * The product_id is not a valid or currently tradable product for this request.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderProductIdInvalid = 'ORDER_PRODUCT_ID_INVALID',
  /**
   * The product_id field is required for this request.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderProductIdRequired = 'ORDER_PRODUCT_ID_REQUIRED',
  /**
   * The client_order_id field is required to accept a quote.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderClientOrderIdRequired = 'ORDER_CLIENT_ORDER_ID_REQUIRED',
  /**
   * The quote_id field is required to accept a quote.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderQuoteIdRequired = 'ORDER_QUOTE_ID_REQUIRED',
  /**
   * The side field is required and was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderSideRequired = 'ORDER_SIDE_REQUIRED',
  /**
   * The side field is not a supported order side. Specify BUY or SELL.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderSideInvalid = 'ORDER_SIDE_INVALID',
}
