/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CancelAdvancedTransferBadRequestSubcode {
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The advanced transfer request is malformed or fails validation, such as a missing portfolio_id, a missing or unsupported transfer type, or an invalid fund movement.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  AdvancedTransferRequestInvalid = 'ADVANCED_TRANSFER_REQUEST_INVALID',
  /**
   * The advanced_transfer_id provided does not correspond to a transfer that can be cancelled.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  AdvancedTransferIdInvalid = 'ADVANCED_TRANSFER_ID_INVALID',
  /**
   * The advanced transfer cannot be cancelled because it is no longer in a cancellable state.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  AdvancedTransferCancelPreconditionFailed = 'ADVANCED_TRANSFER_CANCEL_PRECONDITION_FAILED',
}
