/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CancelOrderBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The order_id field is missing from the request.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderIdRequired = 'ORDER_ID_REQUIRED',
  /**
   * The order_id provided is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderIdInvalid = 'ORDER_ID_INVALID',
  /**
   * The product_id is not a valid or currently tradable product for this request.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderProductIdInvalid = 'ORDER_PRODUCT_ID_INVALID',
  /**
   * The order is fully filled and can no longer be canceled.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  OrderFullyFilled = 'ORDER_FULLY_FILLED',
  /**
   * The order is currently being replaced (edited) and cannot be canceled while that is in progress.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  OrderBeingReplaced = 'ORDER_BEING_REPLACED',
  /**
   * A cancel request for this order has already been submitted and is still being processed.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderCancelDuplicate = 'ORDER_CANCEL_DUPLICATE',
  /**
   * The FCM trading session associated with this order is not valid for the requested cancel operation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderSessionInvalid = 'ORDER_SESSION_INVALID',
}
