/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateWalletWithdrawalBadRequestSubcode {
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  WalletIdRequired = 'WALLET_ID_REQUIRED',
  WalletIdInvalid = 'WALLET_ID_INVALID',
  WalletRequestInvalid = 'WALLET_REQUEST_INVALID',
  WalletFailedPrecondition = 'WALLET_FAILED_PRECONDITION',
  WalletNetworkInvalid = 'WALLET_NETWORK_INVALID',
  WalletAmountRequired = 'WALLET_AMOUNT_REQUIRED',
  WalletIdempotencyKeyRequired = 'WALLET_IDEMPOTENCY_KEY_REQUIRED',
  WalletIdempotencyKeyInvalid = 'WALLET_IDEMPOTENCY_KEY_INVALID',
  WalletCurrencySymbolRequired = 'WALLET_CURRENCY_SYMBOL_REQUIRED',
  WalletDestinationTypeRequired = 'WALLET_DESTINATION_TYPE_REQUIRED',
  WalletDestinationTypeInvalid = 'WALLET_DESTINATION_TYPE_INVALID',
  WalletCounterpartyIdRequired = 'WALLET_COUNTERPARTY_ID_REQUIRED',
}
