/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateWalletTransferBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The wallet_id field is required but was not included in the request.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletIdRequired = 'WALLET_ID_REQUIRED',
  /**
   * The wallet_id field is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletIdInvalid = 'WALLET_ID_INVALID',
  /**
   * The request contains an invalid argument for this wallet operation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletRequestInvalid = 'WALLET_REQUEST_INVALID',
  /**
   * The wallet request failed a precondition, such as the wallet not being able to accept the requested action.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  WalletFailedPrecondition = 'WALLET_FAILED_PRECONDITION',
  /**
   * The amount field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletAmountRequired = 'WALLET_AMOUNT_REQUIRED',
  /**
   * The idempotency_key field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletIdempotencyKeyRequired = 'WALLET_IDEMPOTENCY_KEY_REQUIRED',
  /**
   * The idempotency_key field is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletIdempotencyKeyInvalid = 'WALLET_IDEMPOTENCY_KEY_INVALID',
  /**
   * The currency_symbol field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletCurrencySymbolRequired = 'WALLET_CURRENCY_SYMBOL_REQUIRED',
  /**
   * The destination wallet ID is required for an internal wallet transfer.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletTransferDestinationRequired = 'WALLET_TRANSFER_DESTINATION_REQUIRED',
  /**
   * The destination wallet ID is not a valid UUID, or is the same as the source wallet_id.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletTransferDestinationInvalid = 'WALLET_TRANSFER_DESTINATION_INVALID',
}
