/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateAllocationBadRequestSubcode {
  PortfolioTypeUnsupported = 'PORTFOLIO_TYPE_UNSUPPORTED',
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  AllocationIdRequired = 'ALLOCATION_ID_REQUIRED',
  AllocationNettingIdRequired = 'ALLOCATION_NETTING_ID_REQUIRED',
  AllocationRequestInvalid = 'ALLOCATION_REQUEST_INVALID',
  AllocationPreconditionFailed = 'ALLOCATION_PRECONDITION_FAILED',
  AllocationSourcePortfolioIdRequired = 'ALLOCATION_SOURCE_PORTFOLIO_ID_REQUIRED',
  AllocationDestinationPortfolioIdRequired = 'ALLOCATION_DESTINATION_PORTFOLIO_ID_REQUIRED',
  AllocationOrdersMixedSides = 'ALLOCATION_ORDERS_MIXED_SIDES',
  AllocationOrdersMixedProducts = 'ALLOCATION_ORDERS_MIXED_PRODUCTS',
  AllocationOrderNotTerminal = 'ALLOCATION_ORDER_NOT_TERMINAL',
  AllocationOrderTooOld = 'ALLOCATION_ORDER_TOO_OLD',
  AllocationOrderAlreadyAllocated = 'ALLOCATION_ORDER_ALREADY_ALLOCATED',
}
