/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateOnchainTransactionBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The wallet_id field is required but was not included in the request.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletIdRequired = 'WALLET_ID_REQUIRED',
  /**
   * The wallet_id field is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletIdInvalid = 'WALLET_ID_INVALID',
  /**
   * The wallet's type does not support this operation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletTypeNotSupported = 'WALLET_TYPE_NOT_SUPPORTED',
  /**
   * The onchain transaction request failed validation because of an invalid parameter, an unsupported wallet type, or a malformed evm_params value.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OnchainTransactionRequestInvalid = 'ONCHAIN_TRANSACTION_REQUEST_INVALID',
  /**
   * The raw_unsigned_txn field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OnchainTransactionRawUnsignedTxnRequired = 'ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_REQUIRED',
  /**
   * The raw_unsigned_txn field is not a valid hex-encoded string.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OnchainTransactionRawUnsignedTxnInvalid = 'ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_INVALID',
  /**
   * The evm_params field is required when the destination wallet is on an EVM-based network.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OnchainTransactionEvmParamsRequired = 'ONCHAIN_TRANSACTION_EVM_PARAMS_REQUIRED',
  /**
   * The evm_params field was provided but the destination wallet is on a non-EVM network, such as Solana, where EVM-specific parameters are not supported.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OnchainTransactionEvmParamsInvalid = 'ONCHAIN_TRANSACTION_EVM_PARAMS_INVALID',
  /**
   * The replaced_transaction_id field is not a valid transaction identifier.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OnchainTransactionReplacedTransactionIdInvalid = 'ONCHAIN_TRANSACTION_REPLACED_TRANSACTION_ID_INVALID',
  /**
   * The disable_dynamic_nonce field must be false when replaced_transaction_id is set to replace an existing transaction.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OnchainTransactionDisableDynamicNonceInvalid = 'ONCHAIN_TRANSACTION_DISABLE_DYNAMIC_NONCE_INVALID',
  /**
   * The chain_id field is required within evm_params for transactions on EVM-based networks.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OnchainTransactionChainIdRequired = 'ONCHAIN_TRANSACTION_CHAIN_ID_REQUIRED',
  /**
   * The chain_id field is not a valid integer, or it must be 1 when using the Flashbots RPC endpoint.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OnchainTransactionChainIdInvalid = 'ONCHAIN_TRANSACTION_CHAIN_ID_INVALID',
  /**
   * The network_name field is required when submitting a transaction through a custom RPC endpoint.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OnchainTransactionNetworkNameRequired = 'ONCHAIN_TRANSACTION_NETWORK_NAME_REQUIRED',
  /**
   * The custom RPC endpoint provided cannot be used, either because the wallet is not on an EVM-based network or because the call to that endpoint failed.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OnchainTransactionRpcUrlInvalid = 'ONCHAIN_TRANSACTION_RPC_URL_INVALID',
}
