/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateQuoteRequestBadRequestSubcode {
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  BuyingPowerCurrencyInvalid = 'BUYING_POWER_CURRENCY_INVALID',
  BuyingPowerFailedPrecondition = 'BUYING_POWER_FAILED_PRECONDITION',
  OrderRequestInvalid = 'ORDER_REQUEST_INVALID',
  OrderProductIdInvalid = 'ORDER_PRODUCT_ID_INVALID',
  OrderFailedPrecondition = 'ORDER_FAILED_PRECONDITION',
  OrderProductIdRequired = 'ORDER_PRODUCT_ID_REQUIRED',
  OrderSideRequired = 'ORDER_SIDE_REQUIRED',
  OrderResourceNotFound = 'ORDER_RESOURCE_NOT_FOUND',
  OrderSideInvalid = 'ORDER_SIDE_INVALID',
  OrderSizeInvalid = 'ORDER_SIZE_INVALID',
  OrderPriceInvalid = 'ORDER_PRICE_INVALID',
  OrderClientQuoteIdRequired = 'ORDER_CLIENT_QUOTE_ID_REQUIRED',
  OrderQuoteDurationInvalid = 'ORDER_QUOTE_DURATION_INVALID',
}
