/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateWalletBadRequestSubcode {
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  WalletTypeNotSupported = 'WALLET_TYPE_NOT_SUPPORTED',
  WalletRequestInvalid = 'WALLET_REQUEST_INVALID',
  WalletOnchainSymbolsNotAllowed = 'WALLET_ONCHAIN_SYMBOLS_NOT_ALLOWED',
  WalletFailedPrecondition = 'WALLET_FAILED_PRECONDITION',
  WalletNetworkIdRequired = 'WALLET_NETWORK_ID_REQUIRED',
  WalletNetworkInvalid = 'WALLET_NETWORK_INVALID',
  WalletOnchainSetupUnavailable = 'WALLET_ONCHAIN_SETUP_UNAVAILABLE',
  WalletNameRequired = 'WALLET_NAME_REQUIRED',
  WalletSymbolRequired = 'WALLET_SYMBOL_REQUIRED',
  WalletNetworkFamilyRequired = 'WALLET_NETWORK_FAMILY_REQUIRED',
  WalletNetworkFamilyNotAllowed = 'WALLET_NETWORK_FAMILY_NOT_ALLOWED',
  WalletNetworkTypeRequired = 'WALLET_NETWORK_TYPE_REQUIRED',
}
