/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateWalletBadRequestSubcode {
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The wallet's type does not support this operation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletTypeNotSupported = 'WALLET_TYPE_NOT_SUPPORTED',
  /**
   * The request contains an invalid argument for this wallet operation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletRequestInvalid = 'WALLET_REQUEST_INVALID',
  /**
   * The symbols filter cannot be set when the wallet type is ONCHAIN.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletOnchainSymbolsNotAllowed = 'WALLET_ONCHAIN_SYMBOLS_NOT_ALLOWED',
  /**
   * The wallet request failed a precondition, such as the wallet not being able to accept the requested action.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  WalletFailedPrecondition = 'WALLET_FAILED_PRECONDITION',
  /**
   * The network_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletNetworkIdRequired = 'WALLET_NETWORK_ID_REQUIRED',
  /**
   * The network identifier is malformed. It must be in the format \{network_id\}-\{network_type\} (e.g. base-mainnet), with no spaces, and each part no longer than 20 characters.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletNetworkInvalid = 'WALLET_NETWORK_INVALID',
  /**
   * Onchain wallet setup for this network family has not been completed yet, and must be done through the Prime web application before creating this wallet via the API.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  WalletOnchainSetupUnavailable = 'WALLET_ONCHAIN_SETUP_UNAVAILABLE',
  /**
   * The name field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletNameRequired = 'WALLET_NAME_REQUIRED',
  /**
   * The symbol field is required for wallet types other than ONCHAIN.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletSymbolRequired = 'WALLET_SYMBOL_REQUIRED',
  /**
   * The network_family field is required when wallet_type is ONCHAIN.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletNetworkFamilyRequired = 'WALLET_NETWORK_FAMILY_REQUIRED',
  /**
   * The network_family field must not be set when wallet_type is not ONCHAIN.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletNetworkFamilyNotAllowed = 'WALLET_NETWORK_FAMILY_NOT_ALLOWED',
  /**
   * The type field on the network object is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletNetworkTypeRequired = 'WALLET_NETWORK_TYPE_REQUIRED',
}
