/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateOrderForbiddenSubcode {
  /**
   * You do not have permission to access this resource with the current API key.
   *
   * Error code: PERMISSION_DENIED (HTTP 403)
   */
  AuthResourceAccessDenied = 'AUTH_RESOURCE_ACCESS_DENIED',
  /**
   * A valid client certificate was not presented with the request.
   *
   * Error code: PERMISSION_DENIED (HTTP 403)
   */
  MtlsCertificateRequired = 'MTLS_CERTIFICATE_REQUIRED',
  /**
   * The presented client certificate has been revoked.
   *
   * Error code: PERMISSION_DENIED (HTTP 403)
   */
  MtlsCertificateRevoked = 'MTLS_CERTIFICATE_REVOKED',
  /**
   * The presented client certificate is not a valid identity for this organization or environment.
   *
   * Error code: PERMISSION_DENIED (HTTP 403)
   */
  MtlsCertificateInvalid = 'MTLS_CERTIFICATE_INVALID',
  /**
   * You do not have permission to view buying power for the requested portfolio and currency pair.
   *
   * Error code: PERMISSION_DENIED (HTTP 403)
   */
  BuyingPowerPermissionDenied = 'BUYING_POWER_PERMISSION_DENIED',
}
