/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreatePortfolioAddressBookEntryBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The address book request contains an invalid argument, such as a malformed address or currency_symbol.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  AddressBookInvalidArgument = 'ADDRESS_BOOK_INVALID_ARGUMENT',
  /**
   * The address book entry could not be created or retrieved because a precondition was not met.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  AddressBookFailedPrecondition = 'ADDRESS_BOOK_FAILED_PRECONDITION',
  /**
   * The address field is required to create an address book entry.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  AddressBookAddressRequired = 'ADDRESS_BOOK_ADDRESS_REQUIRED',
  /**
   * The currency_symbol field is required to create an address book entry.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  AddressBookCurrencySymbolRequired = 'ADDRESS_BOOK_CURRENCY_SYMBOL_REQUIRED',
  /**
   * The name field is required to create an address book entry.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  AddressBookNameRequired = 'ADDRESS_BOOK_NAME_REQUIRED',
}
