/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateQuoteRequestBadRequestSubcode {
  /**
   * The entity_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The requested currency pair is not valid or not supported for buying power.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  BuyingPowerCurrencyInvalid = 'BUYING_POWER_CURRENCY_INVALID',
  /**
   * The buying power request failed a precondition, such as the portfolio not being in a state that supports the requested currency pair.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  BuyingPowerFailedPrecondition = 'BUYING_POWER_FAILED_PRECONDITION',
  /**
   * The order request failed validation, such as an invalid stp_id, price, size, or commission_rate.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderRequestInvalid = 'ORDER_REQUEST_INVALID',
  /**
   * The product_id is not a valid or currently tradable product for this request.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderProductIdInvalid = 'ORDER_PRODUCT_ID_INVALID',
  /**
   * The order request could not be completed because a required precondition was not met, for example an account needed to process the order could not be found or created.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  OrderFailedPrecondition = 'ORDER_FAILED_PRECONDITION',
  /**
   * The product_id field is required for this request.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderProductIdRequired = 'ORDER_PRODUCT_ID_REQUIRED',
  /**
   * The side field is required and was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderSideRequired = 'ORDER_SIDE_REQUIRED',
  /**
   * No order matching the given order_id was found for this portfolio.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderResourceNotFound = 'ORDER_RESOURCE_NOT_FOUND',
  /**
   * The side field is not a supported order side. Specify BUY or SELL.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderSideInvalid = 'ORDER_SIDE_INVALID',
  /**
   * The order size is invalid, either because it could not be parsed as a number or because both base_quantity and quote_value were specified.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderSizeInvalid = 'ORDER_SIZE_INVALID',
  /**
   * The order price is invalid, either because limit_price could not be parsed as a number or because a limit price was supplied for a market order.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderPriceInvalid = 'ORDER_PRICE_INVALID',
  /**
   * The client_quote_id field is required for a quote request.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  OrderClientQuoteIdRequired = 'ORDER_CLIENT_QUOTE_ID_REQUIRED',
  /**
   * The quote_duration_ms field is outside the allowed range.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  OrderQuoteDurationInvalid = 'ORDER_QUOTE_DURATION_INVALID',
}
