/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateConversionBadRequestSubcode {
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The wallet_id field is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletIdInvalid = 'WALLET_ID_INVALID',
  /**
   * The destination field is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ConversionDestinationInvalid = 'CONVERSION_DESTINATION_INVALID',
  /**
   * The idempotency_key field is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ConversionIdempotencyKeyInvalid = 'CONVERSION_IDEMPOTENCY_KEY_INVALID',
  /**
   * The amount field is not a valid decimal number.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ConversionAmountInvalid = 'CONVERSION_AMOUNT_INVALID',
  /**
   * The source_symbol field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  ConversionSourceSymbolRequired = 'CONVERSION_SOURCE_SYMBOL_REQUIRED',
  /**
   * The destination field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  ConversionDestinationRequired = 'CONVERSION_DESTINATION_REQUIRED',
  /**
   * The conversion request was rejected as invalid, for example due to an unsupported asset pair or a duplicate transaction.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ConversionRequestInvalid = 'CONVERSION_REQUEST_INVALID',
  /**
   * The conversion could not be completed because a required condition was not met, such as insufficient available balance in the source wallet.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  ConversionFailedPrecondition = 'CONVERSION_FAILED_PRECONDITION',
}
