/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum CreateConversionBadRequestSubcode {
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  WalletIdInvalid = 'WALLET_ID_INVALID',
  ConversionDestinationInvalid = 'CONVERSION_DESTINATION_INVALID',
  ConversionIdempotencyKeyInvalid = 'CONVERSION_IDEMPOTENCY_KEY_INVALID',
  ConversionAmountInvalid = 'CONVERSION_AMOUNT_INVALID',
  ConversionSourceSymbolRequired = 'CONVERSION_SOURCE_SYMBOL_REQUIRED',
  ConversionDestinationRequired = 'CONVERSION_DESTINATION_REQUIRED',
  ConversionRequestInvalid = 'CONVERSION_REQUEST_INVALID',
  ConversionFailedPrecondition = 'CONVERSION_FAILED_PRECONDITION',
}
