/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetBuyingPowerBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The base_currency field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  BuyingPowerBaseCurrencyRequired = 'BUYING_POWER_BASE_CURRENCY_REQUIRED',
  /**
   * The quote_currency field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  BuyingPowerQuoteCurrencyRequired = 'BUYING_POWER_QUOTE_CURRENCY_REQUIRED',
  /**
   * The requested currency pair is not valid or not supported for buying power.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  BuyingPowerCurrencyInvalid = 'BUYING_POWER_CURRENCY_INVALID',
  /**
   * The buying power request failed a precondition, such as the portfolio not being in a state that supports the requested currency pair.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  BuyingPowerFailedPrecondition = 'BUYING_POWER_FAILED_PRECONDITION',
}
