/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetLocateAvailabilitiesBadRequestSubcode {
  /**
   * The entity_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  EntityIdRequired = 'ENTITY_ID_REQUIRED',
  /**
   * The entity_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  /**
   * The locate_date value is not a valid YYYY-MM-DD date.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  LocateDateInvalid = 'LOCATE_DATE_INVALID',
  /**
   * The stock locate request is invalid — for example, both locate_date and locate_ids are missing, or the requested locate_date is in the past or too far in the future.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  LocateRequestInvalid = 'LOCATE_REQUEST_INVALID',
  /**
   * The stock locate request failed a precondition, such as no availability for the requested currency or portfolio margin not being enabled.
   *
   * Error code: FAILED_PRECONDITION (HTTP 400)
   */
  LocateFailedPrecondition = 'LOCATE_FAILED_PRECONDITION',
  /**
   * The locate_date field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  LocateDateRequired = 'LOCATE_DATE_REQUIRED',
}
