/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetMarginSummariesBadRequestSubcode {
  /**
   * The entity_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  EntityIdRequired = 'ENTITY_ID_REQUIRED',
  /**
   * The entity_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  /**
   * The start_date value is not a valid RFC 3339 timestamp.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  FinancingStartDateInvalid = 'FINANCING_START_DATE_INVALID',
  /**
   * The end_date value is not a valid RFC 3339 timestamp.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  FinancingEndDateInvalid = 'FINANCING_END_DATE_INVALID',
  /**
   * The requested start_date to end_date range exceeds the maximum trailing period of 3 months for margin summaries.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  MarginSummaryRangeInvalid = 'MARGIN_SUMMARY_RANGE_INVALID',
  /**
   * The margin summaries request failed a precondition, such as the entity not being in a state that supports margin summaries.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  MarginSummaryFailedPrecondition = 'MARGIN_SUMMARY_FAILED_PRECONDITION',
}
