/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetPortfolioTransactionsBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The limit field exceeds the maximum number of transactions that can be returned in a single request.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionLimitExceeded = 'TRANSACTION_LIMIT_EXCEEDED',
  /**
   * The cursor field is not a valid pagination token. Omit it or use the cursor value returned from a previous response.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionCursorInvalid = 'TRANSACTION_CURSOR_INVALID',
  /**
   * The travel_rule_status filter contains a value that is not recognized.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionTravelRuleStatusInvalid = 'TRANSACTION_TRAVEL_RULE_STATUS_INVALID',
  /**
   * The combination of request filters is invalid, such as specifying symbols together with the ONCHAIN_TRANSACTION type.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionFilterInvalid = 'TRANSACTION_FILTER_INVALID',
  /**
   * One or more request parameters, such as portfolio_id, transaction_ids, cursor, or limit, failed validation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionParamsInvalid = 'TRANSACTION_PARAMS_INVALID',
}
