/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetPortfolioAllocationsBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * One or more allocation request fields, such as product_id, order_ids, allocation_legs, or size_type, are missing or invalid.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  AllocationRequestInvalid = 'ALLOCATION_REQUEST_INVALID',
  /**
   * The start_date field is required when listing portfolio allocations.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  AllocationStartDateRequired = 'ALLOCATION_START_DATE_REQUIRED',
  /**
   * The limit field exceeds the maximum number of allocations that can be returned in a single request.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  AllocationLimitExceeded = 'ALLOCATION_LIMIT_EXCEEDED',
}
