/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetPortfolioActivitiesBadRequestSubcode {
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The activity request contains an invalid argument, such as a malformed filter or identifier.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ActivityRequestInvalid = 'ACTIVITY_REQUEST_INVALID',
  /**
   * The categories field contains a value that is not a supported activity category.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ActivityCategoryInvalid = 'ACTIVITY_CATEGORY_INVALID',
  /**
   * The start_time or end_time field is not a valid RFC 3339 timestamp, or end_time is earlier than start_time.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ActivityTimeRangeInvalid = 'ACTIVITY_TIME_RANGE_INVALID',
  /**
   * The statuses field contains a value that is not a supported activity status.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ActivityStatusInvalid = 'ACTIVITY_STATUS_INVALID',
}
