/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetPostTradeCreditNotFoundSubcode {
  /**
   * No resource was found matching the request, or you do not have access to it.
   *
   * Error code: RESOURCE_NOT_FOUND (HTTP 404)
   */
  AuthResourceNotFound = 'AUTH_RESOURCE_NOT_FOUND',
  /**
   * Post-trade credit information is not available for this portfolio because its entity has portfolio margin enabled.
   *
   * Error code: RESOURCE_NOT_FOUND (HTTP 404)
   */
  FinancingPtcDisabledForPmEntity = 'FINANCING_PTC_DISABLED_FOR_PM_ENTITY',
}
