/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetTFTieredPricingFeesBadRequestSubcode {
  EntityIdRequired = 'ENTITY_ID_REQUIRED',
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  TieredPricingEffectiveAtInvalid = 'TIERED_PRICING_EFFECTIVE_AT_INVALID',
  TieredPricingRequestInvalid = 'TIERED_PRICING_REQUEST_INVALID',
  TieredPricingFailedPrecondition = 'TIERED_PRICING_FAILED_PRECONDITION',
}
