/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetTransactionTravelRuleDataNotFoundSubcode {
  /**
   * No resource was found matching the request, or you do not have access to it.
   *
   * Error code: RESOURCE_NOT_FOUND (HTTP 404)
   */
  AuthResourceNotFound = 'AUTH_RESOURCE_NOT_FOUND',
  /**
   * The requested transaction could not be found for this portfolio, or a transaction referenced in transaction_ids does not belong to it.
   *
   * Error code: RESOURCE_NOT_FOUND (HTTP 404)
   */
  TransactionNotFound = 'TRANSACTION_NOT_FOUND',
  /**
   * No travel rule data is available for the specified transaction.
   *
   * Error code: RESOURCE_NOT_FOUND (HTTP 404)
   */
  TransactionTravelRuleDataNotFound = 'TRANSACTION_TRAVEL_RULE_DATA_NOT_FOUND',
}
