/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetWalletDepositInstructionsBadRequestSubcode {
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  AssetRequestInvalid = 'ASSET_REQUEST_INVALID',
  WalletIdRequired = 'WALLET_ID_REQUIRED',
  WalletIdInvalid = 'WALLET_ID_INVALID',
  WalletDepositTypeRequired = 'WALLET_DEPOSIT_TYPE_REQUIRED',
  WalletMetadataInvalid = 'WALLET_METADATA_INVALID',
  WalletNetworkRequired = 'WALLET_NETWORK_REQUIRED',
  WalletNotDepositable = 'WALLET_NOT_DEPOSITABLE',
  WalletDepositRequestInvalid = 'WALLET_DEPOSIT_REQUEST_INVALID',
  WalletFailedPrecondition = 'WALLET_FAILED_PRECONDITION',
}
