/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum GetXMLiquidationBadRequestSubcode {
  /**
   * The entity_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  EntityIdRequired = 'ENTITY_ID_REQUIRED',
  /**
   * The entity_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  /**
   * The cross margin or funding settings request contains an invalid argument, such as a portfolio_id, entity_id, or liquidation_id that does not belong to the specified entity.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  CrossMarginInvalidArgument = 'CROSS_MARGIN_INVALID_ARGUMENT',
  /**
   * The cross margin or funding settings request failed a precondition, such as the entity or portfolio not being in a state that supports the requested operation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  CrossMarginFailedPrecondition = 'CROSS_MARGIN_FAILED_PRECONDITION',
}
