/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum ListWeb3WalletBalancesBadRequestSubcode {
  /**
   * The portfolio_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  /**
   * The portfolio_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  /**
   * The wallet_id field is required but was not included in the request.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  WalletIdRequired = 'WALLET_ID_REQUIRED',
  /**
   * The wallet_id field is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletIdInvalid = 'WALLET_ID_INVALID',
  /**
   * The wallet's type does not support this operation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletTypeNotSupported = 'WALLET_TYPE_NOT_SUPPORTED',
  /**
   * The limit field is outside the allowed range for this request.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletBalancesLimitInvalid = 'WALLET_BALANCES_LIMIT_INVALID',
  /**
   * The visibility_statuses filter contains more values than are allowed.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  WalletVisibilityStatusesInvalid = 'WALLET_VISIBILITY_STATUSES_INVALID',
}
