/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum ListEntityBalancesBadRequestSubcode {
  /**
   * The entity_id is not a valid UUID.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  /**
   * The limit parameter for entity balances is out of the valid range.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityBalancesLimitInvalid = 'ENTITY_BALANCES_LIMIT_INVALID',
  /**
   * The entity balances request contains an invalid cursor or filter.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  EntityBalancesInvalidArgument = 'ENTITY_BALANCES_INVALID_ARGUMENT',
}
