/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum ListTransactionValidatorsBadRequestSubcode {
  /**
   * The transaction does not support the requested operation, such as submitting travel rule data for a transaction that is not a deposit.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionTypeUnsupported = 'TRANSACTION_TYPE_UNSUPPORTED',
  /**
   * One or more values in transaction_ids are missing, exceed the maximum allowed count, or are not valid UUIDs.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionIdsInvalid = 'TRANSACTION_IDS_INVALID',
  /**
   * One or more request parameters, such as portfolio_id, transaction_ids, cursor, or limit, failed validation.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  TransactionParamsInvalid = 'TRANSACTION_PARAMS_INVALID',
}
