/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum OrderPreviewBadRequestSubcode {
  EntityIdInvalid = 'ENTITY_ID_INVALID',
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  BuyingPowerCurrencyInvalid = 'BUYING_POWER_CURRENCY_INVALID',
  BuyingPowerFailedPrecondition = 'BUYING_POWER_FAILED_PRECONDITION',
  OrderRequestInvalid = 'ORDER_REQUEST_INVALID',
  OrderTypeBlockUnsupported = 'ORDER_TYPE_BLOCK_UNSUPPORTED',
  OrderTypeRfqUnsupported = 'ORDER_TYPE_RFQ_UNSUPPORTED',
  OrderFokNotEnabled = 'ORDER_FOK_NOT_ENABLED',
  OrderStopLimitNotEnabled = 'ORDER_STOP_LIMIT_NOT_ENABLED',
  OrderPegNotEnabled = 'ORDER_PEG_NOT_ENABLED',
  OrderDuplicateClientOrderId = 'ORDER_DUPLICATE_CLIENT_ORDER_ID',
  OrderRejected = 'ORDER_REJECTED',
  OrderProductIdInvalid = 'ORDER_PRODUCT_ID_INVALID',
  OrderFailedPrecondition = 'ORDER_FAILED_PRECONDITION',
  OrderSideInvalid = 'ORDER_SIDE_INVALID',
  OrderSizeRequired = 'ORDER_SIZE_REQUIRED',
  OrderSizeInvalid = 'ORDER_SIZE_INVALID',
  OrderDisplaySizeInvalid = 'ORDER_DISPLAY_SIZE_INVALID',
  OrderPriceInvalid = 'ORDER_PRICE_INVALID',
  OrderStopPriceInvalid = 'ORDER_STOP_PRICE_INVALID',
  OrderTimeInForceInvalid = 'ORDER_TIME_IN_FORCE_INVALID',
  OrderTimeRangeInvalid = 'ORDER_TIME_RANGE_INVALID',
  OrderPegOffsetTypeInvalid = 'ORDER_PEG_OFFSET_TYPE_INVALID',
}
