/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum PortfolioStakingInitiateBadRequestSubcode {
  PortfolioIdRequired = 'PORTFOLIO_ID_REQUIRED',
  PortfolioIdInvalid = 'PORTFOLIO_ID_INVALID',
  WalletExternalIdInvalid = 'WALLET_EXTERNAL_ID_INVALID',
  StakingRequestInvalid = 'STAKING_REQUEST_INVALID',
  StakingCurrencyUnsupported = 'STAKING_CURRENCY_UNSUPPORTED',
  StakingAmountRequired = 'STAKING_AMOUNT_REQUIRED',
  StakingAmountInvalid = 'STAKING_AMOUNT_INVALID',
  StakingNoEligibleWallets = 'STAKING_NO_ELIGIBLE_WALLETS',
  StakingBalanceNotFound = 'STAKING_BALANCE_NOT_FOUND',
  StakingAmountExceedsBondableBalance = 'STAKING_AMOUNT_EXCEEDS_BONDABLE_BALANCE',
  StakingIdempotencyKeyRequired = 'STAKING_IDEMPOTENCY_KEY_REQUIRED',
  StakingIdempotencyKeyInvalid = 'STAKING_IDEMPOTENCY_KEY_INVALID',
  StakingCurrencySymbolRequired = 'STAKING_CURRENCY_SYMBOL_REQUIRED',
}
