/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum PreviewUnstakeBadRequestSubcode {
  StakingCurrencyUnsupported = 'STAKING_CURRENCY_UNSUPPORTED',
  StakingAmountRequired = 'STAKING_AMOUNT_REQUIRED',
  StakingAmountInvalid = 'STAKING_AMOUNT_INVALID',
  StakingInsufficientBalance = 'STAKING_INSUFFICIENT_BALANCE',
  StakingWalletOrPortfolioInvalid = 'STAKING_WALLET_OR_PORTFOLIO_INVALID',
  StakingAmountExceedsUnbondableBalance = 'STAKING_AMOUNT_EXCEEDS_UNBONDABLE_BALANCE',
  StakingWalletColdAddressNotFound = 'STAKING_WALLET_COLD_ADDRESS_NOT_FOUND',
}
