/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum RotateAPIKeyBadRequestSubcode {
  /**
   * The duration_seconds field exceeds the maximum allowed rotation timespan of 30 days.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ApiKeyInvalidDuration = 'API_KEY_INVALID_DURATION',
  /**
   * A rotation has already been initiated for this API key. Only one rotation may be pending at a time.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  ApiKeyAlreadyRotated = 'API_KEY_ALREADY_ROTATED',
}
