/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum SetFcmSettingsBadRequestSubcode {
  /**
   * The entity_id field is required but was not provided.
   *
   * Error code: REQUIRED_FIELD_MISSING (HTTP 400)
   */
  EntityIdRequired = 'ENTITY_ID_REQUIRED',
  /**
   * The request contained an invalid argument for this futures operation, such as an unrecognized entity_id or an invalid amount or currency.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  FcmInvalidArgument = 'FCM_INVALID_ARGUMENT',
  /**
   * The target_derivatives_excess field must be a valid, non-negative decimal value.
   *
   * Error code: VALIDATION_ERROR (HTTP 400)
   */
  FcmTargetDerivativesExcessInvalid = 'FCM_TARGET_DERIVATIVES_EXCESS_INVALID',
}
